### ISSUE TITLE
Cannot read property 'child__rSFields' of undefined.

### ISSUE THREAD

**Issue by jrattanpal** [forcedotcom/SFDX-Data-Move-Utility#105]
I got this error when fetching data from one org. It just says from "undefined" but not sure where or why this error is happening. 

Is it possible to add more details to easily figure out what maybe causing this issue?

[12:41:20.345][ERROR] Execution of the command was ABORTED due to unexpected error: Cannot read property 'child__rSFields' of undefined.
[12:41:20.347] [STACK TRACE] TypeError: Cannot read property 'child__rSFields' of undefined
    at Script.processObjectsMetadataAsync (/Users/jrattanpal/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/script_models/script.js:148:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[12:41:20.351] Execution of the command sfdmu:run has been finished. Exit code 1 (COMMAND_UNEXPECTED_ERROR).

Log file is attached: 
[2020-06-24__12_40_19.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4826852/2020-06-24__12_40_19.log)

Export file: [export.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4826857/export.txt)

**Comment by hknokh** [comment]
Hello @jrattanpal 
Unfortunatelly, because such kind of errors can be caused due large amount of reasons,  I can't tell you  exactly what happens and you need to debug it on your side. Please follow this article: [https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/8.-Debugging.](https://github.com/forcedotcom/SFDX-Data-Move-Utility/wiki/8.-Debugging.)
for the debugging quick start.  Then let me know your findings.
Thank you!

**Comment by hknokh** [comment]
Hello,
I think the issue is gone.
Please check.
