### ISSUE TITLE
3.4.13: Execution of the command was ABORTED due to unexpected error: Cannot read property 'job' of undefined.

### ISSUE THREAD

**Issue by jrattanpal** [forcedotcom/SFDX-Data-Move-Utility#108]
I upgraded to 3.4.13. Now I get this error when I run the plugin. Log and export files are attached

Command in progress...... done
[ERROR] Execution of the command was ABORTED due to unexpected error: Cannot read property 'job' of undefined.
[STACK TRACE] TypeError: Cannot read property 'job' of undefined
    at ScriptObject.get task [as task] (/Users/jrattanpal/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/script_models/scriptObject.js:70:28)
    at forEach.field (/Users/jrattanpal/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/job_models/migrationJobTask.js:1040:55)
    at Array.forEach (<anonymous>)
    at MigrationJobTask._createFilteredQueries (/Users/jrattanpal/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/job_models/migrationJobTask.js:1037:54)
    at MigrationJobTask.retrieveRecords (/Users/jrattanpal/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/job_models/migrationJobTask.js:430:40)
    at MigrationJob.retrieveRecordsAsync (/Users/jrattanpal/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/job_models/migrationJob.js:169:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Execution of the command sfdmu:run has been finished. Exit code 1 (COMMAND_UNEXPECTED_ERROR).
Total time elapsed: 00h 00m 30s 409ms .

[export.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4831566/export.txt)
[2020-06-25__09_29_53.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4831570/2020-06-25__09_29_53.log)

**Comment by hknokh** [comment]
Please recheck with the updated version 3.4.14
