### ISSUE TITLE
[BUG]-Cannot read property 'referencedObjectType' of undefined when loading with --sourceusername csvfile

### ISSUE THREAD

**Issue by kevdo475** [forcedotcom/SFDX-Data-Move-Utility#111]
**Describe the bug**
```
[ERROR] Execution of the command was ABORTED due to unexpected error: Cannot read property 'referencedObjectType' of undefined.
[STACK TRACE] TypeError: Cannot read property 'referencedObjectType' of undefined
    at Script.processObjectsMetadataAsync (/Users/kdoruibin/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/script_models/script.js:104:56)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Execution of the command sfdmu:run has been finished. Exit code 1 (COMMAND_UNEXPECTED_ERROR).
```

**To Reproduce**
1. Run the plugin from source org to target org
```
sfdx sfdmu:run --sourceusername <source> --targetusername <target> --filelog
```
2. Observe no errors
3. Re-run the plugin with `--sourceusername csvfile`  without modifying any files or export.json
```
sfdx sfdmu:run --sourceusername csvfile --targetusername <target> --filelog
```
4. Observe error

**Expected behavior**

**export.json**
```
{
    "bulkApiVersion": 1.0,
    "bulkApiV1BatchSize": 100,
    "promptOnUpdateError": false,
    "promptOnMissingParentObjects": false,
    "objects": [
        {
            "query": "select Id,Name,tsc_Category__c,tsc_Keyword__c,tsc_Language__c,tsc_Organization__c,tsc_SubCategory__c from tsc_Keywords__c",
            "operation": "Upsert",
            "externalId": "tsc_Keyword__c",
            "useFieldMapping": true,
            "fieldMapping": [
                {
                    "targetObject": "SC_CSD_Keyword__c"
                },
                {
                    "sourceField": "tsc_Category__c",
                    "targetField": "SC_CSD_Category__c"
                },
                {
                    "sourceField": "tsc_Keyword__c",
                    "targetField": "SC_CSD_Keyword__c"
                },
                {
                    "sourceField": "tsc_Language__c",
                    "targetField": "SC_CSD_Language__c"
                },
                {
                    "sourceField": "tsc_SubCategory__c",
                    "targetField": "SC_CSD_Sub_Category__c"
                },
                {
                    "sourceField": "tsc_Organization__c",
                    "targetField": "SC_CSD_Organization__c"
                }
            ]
        },
        {
            "query": "select Id,Name,tsc_LinkText__c,tsc_Market__c,tsc_Rank__c from tsc_UsefulLink__c",
            "operation": "Upsert",
            "externalId": "tsc_LinkText__c",
            "useFieldMapping": true,
            "fieldMapping": [
                {
                    "targetObject": "SC_CSD_Useful_Link__c"
                },
                {
                    "sourceField": "tsc_LinkText__c",
                    "targetField": "SC_CSD_Link_Text__c"
                },
                {
                    "sourceField": "tsc_Market__c",
                    "targetField": "SC_CSD_Market__c"
                },
                {
                    "sourceField": "tsc_Rank__c",
                    "targetField": "SC_CSD_Rank__c"
                }
            ]
        },
        {
            "query": "select Id,SMT_MarketCode__c,Name,SMT_AccountsVisibleToMarket__c,SMT_MigrationID__c from SMT_Market__c",
            "operation": "Upsert",
            "externalId": "SMT_MarketCode__c"
        },
        {
            "query": "select Id,RecordTypeId,SMT_SAPID__c,Name,Type,ParentId,BillingStreet,BillingCity,BillingState,BillingPostalCode,BillingCountry,BillingLatitude,BillingLongitude,BillingGeocodeAccuracy,ShippingStreet,ShippingCity,ShippingState,ShippingPostalCode,ShippingCountry,ShippingLatitude,ShippingLongitude,ShippingGeocodeAccuracy,Phone,Fax,AccountNumber,Website,Sic,Industry,AnnualRevenue,NumberOfEmployees,Ownership,TickerSymbol,Description,Rating,Site,Jigsaw,AccountSource,SicDesc,SMT_AccountGroupId__c,SMT_AccountSFInternalId__c,SMT_AccountSegmentation__c,SMT_Active__c,SMT_CustomerBrands__c,SMT_CustomerCategories__c,SMT_CustomerExperience__c,SMT_CustomersOwnStrategy__c,SMT_District__c,SMT_KeyAccount__c,SMT_Language__c,SMT_Market__r.SMT_MarketCode__c,SMT_MigrationID__c,SMT_NbrofOffices__c,SMT_NbrofProductionSites__c,SMT_OtherInformation__c,SMT_PESent__c,SMT_ProfitMargin__c,SMT_SearchKeyWords__c,SMT_SiteType__c,SMT_Status__c,SMT_StrategicAccount__c,SMT_VisibleToMarket__c from Account",
            "operation": "Upsert",
            "externalId": "SMT_SAPID__c",
            "useValuesMapping": true
        },
        {
            "query": "select Id,Email,AccountId,LastName,FirstName,Salutation,MailingStreet,MailingCity,MailingState,MailingPostalCode,MailingCountry,MailingLatitude,MailingLongitude,MailingGeocodeAccuracy,Phone,Fax,MobilePhone,ReportsToId,Title,Department,EmailBouncedReason,EmailBouncedDate,Jigsaw,IndividualId,SMT_Department__c,SMT_Language__c,SMT_MigrationID__c,SMT_SAPContactBPID__c from Contact",
            "operation": "Upsert",
            "externalId": "Email",
            "useValuesMapping": true
        },
        {
            "query": "select Id,SMT_Account__c,SMT_User__c,SMT_ExternalId__c,SMT_TeamRole__c from SMT_AccountTeamMember__c",
            "operation": "Upsert",
            "externalId": "SMT_ExternalId__c"
        },
        {
            "query": "select Id,CreatedDate,CaseNumber,ClosedDate,Subject,SuppliedEmail,ContactId,AccountId,ParentId,SuppliedName,SuppliedPhone,SuppliedCompany,Type,Status,Reason,Origin,Priority,Description,IsEscalated,Comments,tsc_MilestoneTargetDate__c,tsc_MissedSLA__c,tsc_Organization__c,tsc_ReasonMissingSLA__c,tsc_ReasonTransferred__c from Case limit 2000",
            "operation": "Upsert",
            "externalId": "CaseNumber",
            "useFieldMapping": true,
            "fieldMapping": [
                {
                    "sourceField": "tsc_MilestoneTargetDate__c",
                    "targetField": "SC_CSD_Milestone_Target_Date__c"
                },
                {
                    "sourceField": "tsc_MissedSLA__c",
                    "targetField": "SC_CSD_Missed_SLA__c"
                },
                {
                    "sourceField": "tsc_Organization__c",
                    "targetField": "SC_CSD_Organization__c"
                },
                {
                    "sourceField": "tsc_ReasonMissingSLA__c",
                    "targetField": "SC_CSD_Reason_Missing_SLA__c"
                },
                {
                    "sourceField": "tsc_ReasonTransferred__c",
                    "targetField": "SC_CSD_Reason_Transferred__c"
                },
                {
                    "sourceField": "CaseNumber",
                    "targetField": "SC_CSD_Migration_ID__c"
                }
            ]
        },
        {
            "query": "select Id,CreatedDate,ParentId,FromAddress,FromName,ToAddress,CcAddress,BccAddress,Incoming,MessageDate,MessageIdentifier,Status,Headers,Subject,TextBody,HtmlBody from EmailMessage order by createddate desc limit 1000",
            "operation": "Upsert",
            "externalId": "MessageDate;FromAddress;ToAddress"
        }
    ]
}
```

**logs**
[2020-06-26__10_45_16.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4835923/2020-06-26__10_45_16.log)

**Comment by kevdo475** [comment]
@hknokh I did some initial debugging and the error seems to be happening for the object (EmailMessage) that I have set up with a composite external Id. This bug might possibly be an overlooked area of the code in terms of handling composite external Ids?
![image](https://user-images.githubusercontent.com/25485055/85841582-9920c980-b79e-11ea-8728-621d4ca78148.png)

**Comment by hknokh** [comment]
Hello @kevdo475 
Thx for the help in debugging.
I think it should work. Check if the fix is not affected something else.

**Comment by hknokh** [comment]
I could not reproduce this issue in any way and fixed it in a  blind mode ot use if it is really resolved and need rechecking or possible debugging again on your side.

**Comment by kevdo475** [comment]
@hknokh The value is undefined.

**Comment by hknokh** [comment]
Ok, this is what I expected, so let you try to migrate again

**Comment by hknokh** [comment]
Update the plugin of course

**Comment by kevdo475** [comment]
@hknokh Looks like another error popped up now, probably the same root cause.
```
[STACK TRACE] TypeError: Cannot read property 'lookup' of undefined
    at MigrationJobTask.repairCSV (/Users/kdoruibin/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/job_models/migrationJobTask.js:121:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Execution of the command sfdmu:run has been finished. Exit code 1 (COMMAND_UNEXPECTED_ERROR).
```

**Comment by hknokh** [comment]
Ok, i need something to isolate the root case. Pause the execution at the point displayed  on your screenshot where thisField is undefined, then please locate and stingify ENTIRE related "script" object and send me to analyse values to my email, not share it here.

**Comment by hknokh** [comment]
Without this I can't help you, because can't reproduce. The problem that thisField should not be undefined at aby case because of the logic how fieldsInQueryMap property is generated. So need deep diving into this issue.

**Comment by hknokh** [comment]
I think thi is good now (v3.4.17)
