### ISSUE TITLE
Execution of the command was ABORTED due to unexpected error: Cannot read property 'job' of undefined.

### ISSUE THREAD

**Issue by geza-mandli** [forcedotcom/SFDX-Data-Move-Utility#126]
**Describe the bug**
Hi,

I got thee following error when I tried to export a pretty complex object to CSV file. 
[2020-07-02 11:10:44.384] [STACK TRACE] TypeError: Cannot read property 'job' of undefined
at ScriptObject.get task [as task] (----/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/script_models/scriptObject.js:70:28)
at forEach.field (-----/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/job_models/migrationJobTask.js:1044:55)
at Array.forEach ()
at MigrationJobTask._createFilteredQueries (------/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/job_models/migrationJobTask.js:1041:54)
at MigrationJobTask.retrieveRecords (-------/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/job_models/migrationJobTask.js:434:40)
at MigrationJob.retrieveRecordsAsync (-------/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/job_models/migrationJob.js:169:36)
at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-07-02 11:10:44.385] Execution of the command sfdmu:run has been finished. Exit code 1 (COMMAND_UNEXPECTED_ERROR).
[2020-07-02 11:10:44.385] Total time elapsed: 00h 00m 28s 303ms .
[2020-07-02 11:10:44.381] [ERROR] Execution of the command was ABORTED due to unexpected error: Cannot read property 'job' of undefined.

**To Reproduce**
I used the             "query": "Select all"
There are 261 fields on the object and  29 are custom lookup from this 261 fields

**Expected behavior**
Export the data

**Comment by hknokh** [comment]
Hello, need export.json and log file and please update to the current latest version and try again, because this issue with job undefined was already fixed.

**Comment by geza-mandli** [comment]
Hello,

I used the latest version Running version: 3.4.19. Tried to uninstall and install again, but the result was the same.

**Comment by hknokh** [comment]
Well, provide the latest export.json + log file

**Comment by geza-mandli** [comment]
Hello @hknokh 

I have to check the log file if there is sensitive data in it or not :( But I localized the issue. If I remove the lookup field for Contact object then I can retrieve the data. If I add the Contact lookup field to the package and I add the Contact object on readonly operation then I do not get the error.

Without Readonly Contact object it is failing. For the other 28 lookup fields I do not need to add the object, so it is strange.

[export.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4864388/export.zip)

**Comment by hknokh** [comment]
Hello, @geza-mandli 
I reviewed you export.json file and made some checks. Unfortunatelly, I can't reproduce your issue and so far have no idea how can I help you with resoluition. Such errors may be caused by variety of reasons depend on your data / data model and that is why it should be debugged directly on your local machine. Please, download the source code and try to locate the root case of the issue / or at least do a quick debug in the browser and tell me. You also can open a pull request with the hot fix to the hotfix branch if you want to fix it yourself. 
Your help will be higly appreciated. Thanks.

**Comment by geza-mandli** [comment]
Hello @hknokh 

I think if I add the failed lookup object with Readonly operation and it is working then I can resolve this issue. Thanks you help.
Géza

**Comment by hknokh** [comment]
Hello @geza-mandli 
I applied some patch in 3.4.25
Could you please recheck the failing configuration if it's working?
Thanks!

**Comment by geza-mandli** [comment]
Hello @hknokh ,

Running version: 3.4.25

If I did not add the Contact object with Readonly operation then I still got this error:
[2020-07-03  11:12:10.909] [ERROR] Execution of the command was ABORTED due to unexpected error: Cannot read property 'job' of undefined.
[2020-07-03  11:12:10.911] [STACK TRACE] TypeError: Cannot read property 'job' of undefined

But with 
            "operation": "Readonly",
            "externalId": "Name",
            "mockFields": [],
            "updateWithMockData": false,
            "mockCSVData": false,
            "deleteOldData": false,
            "allRecords": false,
            "useCSVValuesMapping": false,
            "query": "SELECT Id, Name FROM Contact",
            "deleteQuery": ""

It is fine.

Thanks,
Géza

**Comment by geza-mandli** [comment]
Hi @hknokh 


Running version: 3.4.27

[2020-07-03 11:41:11.166] [ERROR] Command initialization error: Malformed select query for the sObject : , error: Error: line 1:0 mismatched input '' expecting SELECT..
[2020-07-03 11:41:11.169] Execution of the command sfdmu:run has been finished. Exit code 2 (COMMAND_INITIALIZATION_ERROR).

**Comment by hknokh** [comment]
Hi, @geza-mandli 
Yes, I know about the mismatched input...)
But v3.4.28 that I just pushed seems to be good.
Can you  give another try, please?
Thank you very much in advance!

**Comment by hknokh** [comment]
3.4.28 should also solve the "job undefined" error, I think

**Comment by geza-mandli** [comment]
Hi @hknokh 

It is working fine now without the additional Readonly Contact object.

Thank you very much your help :)
Géza
