### ISSUE TITLE
[BUG]-TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by kevdo475** [forcedotcom/SFDX-Data-Move-Utility#139]
**Describe the bug**
Error is thrown only when csvfile is set as the target. The follow error is thrown:
```
[STACK TRACE] TypeError: Cannot read property 'toString' of undefined
    at Function.getStrOperation (/Users/kdoruibin/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/script_models/scriptObject.js:357:51)
    at TaskData.getTargetCSVFilename (/Users/kdoruibin/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/common_models/helpers_classes.js:47:72)
    at ___writeToTargetCSVFile (/Users/kdoruibin/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/job_models/migrationJobTask.js:827:67)
    at MigrationJobTask.updateRecords (/Users/kdoruibin/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/job_models/migrationJobTask.js:516:23)
Execution of the command sfdmu:run has been finished. Exit code 1 (COMMAND_UNEXPECTED_ERROR).
```

**To Reproduce**
Run the plugin with csfile as the target.

**Expected behavior**
No errors thrown.

**export.json**
```
{
    "promptOnUpdateError": false,
    "promptOnMissingParentObjects": false,
    "objects": [
        {
            "query": "select Id,SMT_SAPID__c from Account",
            "operation": "ReadOnly",
            "externalId": "SMT_SAPID__c",
            "useValuesMapping": true
        },
        {
            "query": "select Id,Email from Contact",
            "operation": "ReadOnly",
            "externalId": "Email",
            "useValuesMapping": true
        },
        {
            "query": "select Id,SMT_Account__c,SMT_User__c,SMT_ExternalId__c,SMT_TeamRole__c from SMT_AccountTeamMember__c",
            "operation": "Upsert",
            "externalId": "SMT_ExternalId__c"
        },
        {
            "query": "select Id,CreatedDate,CaseNumber,ClosedDate,Subject,SuppliedEmail,ContactId,AccountId,ParentId,SuppliedName,SuppliedPhone,SuppliedCompany,Type,Status,Reason,Origin,Priority,Description,IsEscalated,Comments,tsc_MilestoneTargetDate__c,tsc_MissedSLA__c,tsc_Organization__c,tsc_ReasonMissingSLA__c,tsc_ReasonTransferred__c from Case order by createddate desc",
            "operation": "Readonly",
            "externalId": "CaseNumber",
            "useFieldMapping": true,
            "useValuesMapping": true,
            "fieldMapping": [
                {
                    "sourceField": "tsc_MilestoneTargetDate__c",
                    "targetField": "SC_CSD_Milestone_Target_Date__c"
                },
                {
                    "sourceField": "tsc_MissedSLA__c",
                    "targetField": "SC_CSD_Missed_SLA__c"
                },
                {
                    "sourceField": "tsc_Organization__c",
                    "targetField": "SC_CSD_Organization__c"
                },
                {
                    "sourceField": "tsc_ReasonMissingSLA__c",
                    "targetField": "SC_CSD_Reason_Missing_SLA__c"
                },
                {
                    "sourceField": "tsc_ReasonTransferred__c",
                    "targetField": "SC_CSD_Reason_Transferred__c"
                },
                {
                    "sourceField": "CaseNumber",
                    "targetField": "SC_CSD_Migration_ID__c"
                }
            ]
        },
        {
            "query": "select Id,CreatedDate,ParentId,FromAddress,FromName,ToAddress,CcAddress,BccAddress,Incoming,MessageDate,MessageIdentifier,Status,Headers,Subject,TextBody from EmailMessage where parentId in (select id from case where isclosed=false) order by createddate desc",
            "operation": "Upsert",
            "externalId": "MessageDate;FromAddress;ToAddress"
        },
        {
            "query": "select Body,CreatedDate,Id,InsertedById,IsClosed,IsDeleted,IsRichText,LikeCount,LinkUrl,ParentId$Case,Revision,Status,Title,Type from FeedItem where IsClosed=false and IsDeleted=false and Parent.Type='Case' and Type='TextPost' and parentId in (select id from case where isclosed=false) order by createddate desc",
            "operation": "Upsert",
            "externalId": "CreatedDate"
        }
    ]
}
```

**Log file**
[2020-07-14__12_47_17.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4918340/2020-07-14__12_47_17.log)

**Comment by hknokh** [comment]
Hello @kevdo475 
Probably you have typo in operation ReadOnly instead of Readonly

**Comment by hknokh** [comment]
Since 3.5.4 I added the validation of the operation spelling
