### ISSUE TITLE
Can't start the SFDX-Data-Move-Utility-Desktop-App

### ISSUE THREAD

**Issue by juanlu-github** [forcedotcom/SFDX-Data-Move-Utility#224]
Can't start the SFDX-Data-Move-Utility-Desktop-App: the command npm start returns an error saying that electron was not properly installed. Command output:

npm start

> sfdx-data-move-utility-desktop-app@3.1.7 start SFDX-Data-Move-Utility-Desktop-App
> electron .

SFDX-Data-Move-Utility-Desktop-App\node_modules\electron\index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (SFDX-Data-Move-Utility-Desktop-App\node_modules\electron\index.js:14:11)
    at Object.<anonymous> (SFDX-Data-Move-Utility-Desktop-App\node_modules\electron\index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (SFDX-Data-Move-Utility-Desktop-App\node_modules\electron\cli.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sfdx-data-move-utility-desktop-app@3.1.7 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sfdx-data-move-utility-desktop-app@3.1.7 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     npm-cache\_logs\2020-10-05T06_22_52_893Z-debug.log

I have tried uninstalling and reinstalling with "yarn global add electron", no luck. Same thing with "npm install -g electron".

I am not receiving any errors when executing npm install, nor any of the steps 1-7. I installed the whole thing yesterday for the first time, meaning, npm, node, chocolatey, etc are up-to-date.

**Comment by hknokh** [comment]
Hello, 
Only to remove all, update to the latest  node.js / yarn/ elctron globally and reinstall the app.

**Comment by hknokh** [comment]
Please, use one of our templates to open issue
