### ISSUE TITLE
Error using composite external id

### ISSUE THREAD

**Issue by gidglass** [forcedotcom/SFDX-Data-Move-Utility#23]
I've attempted _several_ combinations of keys from both parent and/or child object and always seem to face the same error:
```
=== RETRIEVING THE SOURCE DATA (STEP 2)...
[2020-05-15  15:45:08.838] [ERROR] Execution of the command was ABORTED due to unexpected error: 
FROM Targeting_Category__c WHERE $$Category__r.Name$Category__r.JSONName__c
                                ^
ERROR at Row:1:Column:86
line 1:86 no viable alternative at character '$'.
[2020-05-15  15:45:08.841] [STACK TRACE] MALFORMED_QUERY: 
FROM Targeting_Category__c WHERE $$Category__r.Name$Category__r.JSONName__c
                                ^
ERROR at Row:1:Column:86
line 1:86 no viable alternative at character '$'
    at HttpApi.getError (/Users/gglas/repositories/SFDX-Data-Move-Utility/node_modules/jsforce/lib/http-api.js:250:13)
    at /Users/gglas/repositories/SFDX-Data-Move-Utility/node_modules/jsforce/lib/http-api.js:95:22
    at tryCallOne (/Users/gglas/repositories/SFDX-Data-Move-Utility/node_modules/promise/lib/core.js:37:12)
    at /Users/gglas/repositories/SFDX-Data-Move-Utility/node_modules/promise/lib/core.js:123:15
    at flush (/Users/gglas/repositories/SFDX-Data-Move-Utility/node_modules/asap/raw.js:50:29)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

In the above snippet, I've tried using two fields on the parent as a "virtual" external id like such:

```
"externalId": "Category__r.Name;Category__r.JSONName__c"
```

**Comment by hknokh** [comment]
Hello, could you provide me your full package.json file?

**Comment by hknokh** [comment]
@gidglass Recently I have completely rewrite the plugin. 
You can update your local version and recheck, may be the issue is now away.
