### ISSUE TITLE
unexpected error: mismatched input 's' expecting ')'.

### ISSUE THREAD

**Issue by ilanhazan** [forcedotcom/SFDX-Data-Move-Utility#24]
I have noticed that I fall a lot with the following exception in several objects:

[2020-05-20  23:13:58.010] {Deal__c} Query string: SELECT Id, Name  FROM  Deal__c WHERE Name IN ('a','b','c','d', 'Innoviz....
[2020-05-20  23:13:58.020] [ERROR] Execution of the command was ABORTED due to unexpected error: line 1:597 mismatched input 's' expecting ')'.
[2020-05-20  23:13:58.023] [STACK TRACE] Error: line 1:597 mismatched input 's' expecting ')'
    at SyntaxErrorListener.syntaxError (/Users/xx/.local/share/sfdx/node_modules/soql-parser-js/dist/index.js:382:15)
    at delegates.forEach.listener (/Users/xx/.local/share/sfdx/node_modules/antlr4ts/ProxyErrorListener.js:37:26)
    at Array.forEach (<anonymous>)
    at ProxyParserErrorListener.syntaxError (/Users/xx/.local/share/sfdx/node_modules/antlr4ts/ProxyErrorListener.js:35:24)
    at SOQLParser.notifyErrorListeners (/Users/xx/.local/share/sfdx/node_modules/antlr4ts/Parser.js:388:22)
    at DefaultErrorStrategy.notifyErrorListeners (/Users/xx/.local/share/sfdx/node_modules/antlr4ts/DefaultErrorStrategy.js:132:20)
    at DefaultErrorStrategy.reportInputMismatch (/Users/xx/.local/share/sfdx/node_modules/antlr4ts/DefaultErrorStrategy.js:287:14)
    at DefaultErrorStrategy.reportError (/Users/xx/.local/share/sfdx/node_modules/antlr4ts/DefaultErrorStrategy.js:115:18)
    at SOQLParser.set_values (/Users/xx/.local/share/sfdx/node_modules/soql-parser-js/dist/index.js:9228:34)
    at SOQLParser.set_based_condition (/Users/xx/.local/share/sfdx/node_modules/soql-parser-js/dist/index.js:9112:34)
[2020-05-20  23:13:58.024] Execution of the command sfdmu:run has been finished. Exit code 1 (COMMAND_UNEXPECTED_ERROR).
[2020-05-20  23:13:58.024] Total time elapsed: 00h 00m 34s 112ms .

This happens when the list in the clause "IN (....)" is too large. When I limit it or making the list smaller, the error disappear. 
However, sometimes the script itself producing the list and I cant control its size. Hence still getting this error.
It is not a syntax error in the export.json queries.

**Comment by hknokh** [comment]
Hello @ilanhazan 

On my side, I could not reporduce the issue with the mailformed query.

I would ask you to provide me an additional info as below:

1. The full execution log file. 
To get this file, just add **--filelog** flag at the end of your cli command. You will see new logs/ subdirectory created at the same directory where your export.json file sits. You have all .log files in this directory.

2. The full version of your export.json file as is, including the long query string.

Thanks!
