### ISSUE TITLE
[APP-Electron failed to install correctly]-failed to launch GUI App

### ISSUE THREAD

**Issue by saimanojaki** [forcedotcom/SFDX-Data-Move-Utility#273]
**Describe the bug**
> sfdx-data-move-utility-desktop-app@3.1.8 start F:\SFDMU\SFDX-Data-Move-Utility-Desktop-App
> electron .

F:\SFDMU\SFDX-Data-Move-Utility-Desktop-App\node_modules\electron\index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (F:\SFDMU\SFDX-Data-Move-Utility-Desktop-App\node_modules\electron\index.js:14:11)
    at Object.<anonymous> (F:\SFDMU\SFDX-Data-Move-Utility-Desktop-App\node_modules\electron\index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (F:\SFDMU\SFDX-Data-Move-Utility-Desktop-App\node_modules\electron\cli.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sfdx-data-move-utility-desktop-app@3.1.8 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sfdx-data-move-utility-desktop-app@3.1.8 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\NEW\AppData\Roaming\npm-cache\_logs\2021-03-12T17_45_38_508Z-debug.log

**To Reproduce**
i have installed all dependency softwares which required for GUI App

**Expected behavior**
Expected to open GUI App 
Expected to Open GUI App

**Comment by hknokh** [comment]
Hello, @saimanojaki 
Sometimes this issue can occur depend on the local configuration,
try to install it locally in the project directory:

npm install electron

**Comment by saimanojaki** [comment]
Hello @hknokh 
Getting Same error not able open App

**Comment by hknokh** [comment]
I upgraded the dependency to the latest electron version.
Please, try to clone the app to a fresh folder and reinstall.

**Comment by hknokh** [comment]
Hi there.
The case has been closed for the current moment.
Feel free to reopen if your issue still persists.
