### ISSUE TITLE
[Question]-Salesforce Org aliases containing spaces make the script crash

### ISSUE THREAD

**Issue by JulienGaiotto** [forcedotcom/SFDX-Data-Move-Utility#279]
**Describe the bug**
When running the ```sfdmu:run``` command, if the org aliases contain spaces, the script crashes.

For instance, the GUI generated the following :
```sfdx sfdmu:run --sourceusername Org Prod --targetusername Org Sandbox --path /Users/path/to/config/ --verbose```

When clicking on "Run the script", I had the following error :
```ERROR running sfdmu:run: Unexpected arguments: Prod, Sandbox```

What makes me think this is not a GUI bug, but more of a core plugin issue is that I figured the double quotes were missing, so I decided I would run the command manually with the quotes, and I launched the following command in my terminal : 
```sfdx sfdmu:run --sourceusername "Org Prod" --targetusername "Org Sandbox" --path /Users/path/to/config/ --verbose```

Bu then I then got the following error :
```
Execution of the command was ABORTED due to unexpected error: Command failed: sfdx force:org:display --targetusername Org Prod
ERROR running force:org:display:  Unexpected argument: Prod
```
The plugin removes the double quotes.

**To Reproduce**
Create an org alias with a space in it, and run the plugin against that alias.

**Expected behavior**
Enclosing the org aliases in double quote, so that it can run properly.

**Log file**
```
[09:44:56.656] {"Running version":"4.0.0"}

[09:44:56.676] [[Core Manifest]] Loading addon manifest ...
[09:44:56.678] [[User Manifest]] Loading addon manifest ...
[09:44:57.131] Connecting to Org Prod using SFDX CLI ...
[09:44:59.995][ERROR] Execution of the command was ABORTED due to unexpected error: Command failed: sfdx force:org:display --targetusername Org Prod
ERROR running force:org:display:  Unexpected argument: Prod
See more help with --help
.
[09:44:59.996] [STACK TRACE] Error: Command failed: sfdx force:org:display --targetusername Org Prod
ERROR running force:org:display:  Unexpected argument: Prod
See more help with --help

    at checkExecSyncError (node:child_process:682:11)
    at Object.execSync (node:child_process:719:15)
    at Function.execSfdx (/Users/julien/.local/share/sfdx/node_modules/sfdmu/lib/modules/components/common_components/common.js:180:36)
    at ScriptOrg._setupConnection (/Users/julien/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/script_models/scriptOrg.js:94:53)
    at ScriptOrg.setupAsync (/Users/julien/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/script_models/scriptOrg.js:41:20)
    at Script.setupAsync (/Users/julien/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/script_models/script.js:129:30)
    at RunCommand.setupAsync (/Users/julien/.local/share/sfdx/node_modules/sfdmu/lib/modules/commands_processors/runCommand.js:47:27)
    at Run.run (/Users/julien/.local/share/sfdx/node_modules/sfdmu/lib/commands/sfdmu/run.js:34:32)
    at Run._run (/Users/julien/.local/share/sfdx/node_modules/@salesforce/command/lib/sfdxCommand.js:81:51)
    at async Config.runCommand (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/config/lib/config.js:173:24)
[09:44:59.997] Execution of the command sfdmu:run has been finished. Exit code 1 (COMMAND_UNEXPECTED_ERROR).
[09:44:59.998] Total time elapsed: 00h 00m 03s 358ms .
```
**Workaround**
Use the ```sfdx alias:set``` command to create other aliases for your orgs, but if you are not aware of that command you may not use that awesome plugin that is sfdmu, which is a complete shame considering the amount of work behind it !

**Comment by hknokh** [comment]
Hi. It is not a bug. This is core sfdx failure before the plugin gets a control over the process. Normally, all the cli flags are handled by the core sfdx api, not by the plugin. I am only reading the flags as is. Probably you need to avoid using spaces in your aliases when working with the sfdmu.
------
The case has been closed for the current moment.
Feel free to reopen if your have any additional question.
