### ISSUE TITLE
Cannot read properties of undefined (reading 'job')

### ISSUE THREAD

**Issue by DanTheGameMan** [forcedotcom/SFDX-Data-Move-Utility#427]
Hey,

I'm trying to run a job from source csvs and I'm getting the following error:

`[12:01:38.698][ERROR] Execution of the command was ABORTED due to unexpected error: Cannot read properties of undefined (reading 'job').
[12:01:38.699][ERROR] [STACK TRACE] TypeError: Cannot read properties of undefined (reading 'job')
    at ScriptObject.get task [as task] (C:\Users\{MyUser}\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\script_models\scriptObject.js:82:28)
    at C:\Users\{MyUser}\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\job_models\migrationJobTask.js:673:135
    at Array.filter (<anonymous>)
    at ___createUpdateData (C:\Users\{MyUser}\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\job_models\migrationJobTask.js:671:62)
    at MigrationJobTask.updateRecords (C:\Users\{MyUser}\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\job_models\migrationJobTask.js:646:30)
    at MigrationJob.updateRecordsAsync (C:\Users\{MyUser}\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\job_models\migrationJob.js:303:54)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RunCommand.executeJobAsync (C:\Users\{MyUser}\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\commands_processors\runCommand.js:84:9)
    at async Function.execute (C:\Users\{MyUser}\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\commands_processors\runCommandExecutor.js:41:13)`

my command looks like:
`sfdx sfdmu:run -u ${alias} -s csvfile --quiet --noprompt --canmodify ${targetDomain} -p ${dataPath}`

I've attached the export.json as a txt
[export.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/8062784/export.txt)
 
Any help is much appreciated - thanks.

**Comment by hknokh** [comment]
@DanTheGameMan 
Thank you for the mention.
I will look into it it
