### ISSUE TITLE
[ISSUE] - error TypeError: Cannot read properties of undefined (reading 'yellow')

### ISSUE THREAD

**Issue by lioram** [forcedotcom/SFDX-Data-Move-Utility#445]
I update the plugin SFDMU to v4.13.0 and I get this error : 

[09:24:01.800] {Account} Number of records to Insert: 220.
[09:24:01.801] {Account} Mapping records to be sent to the API ... The target object: Account.
[09:24:01.803] {Account} The Insert API operation has been started using Bulk API V2.0.
[09:24:02.182] [Job# 7501q000009UokUAAS:Insert] {Account} The job has been created. Uploading data ...
[09:24:02.517] [Batch# 7501q000009UokUAAS:Insert] {Account} The batch has been created. Uploading data ...
[09:24:02.851] [Batch# 7501q000009UokUAAS:Insert] {Account} The data has been uploaded. Processing ...
[09:24:58.364][ERROR] Execution of the command was ABORTED due to unexpected error: Cannot read properties of undefined (reading 'yellow').
[09:24:58.365][ERROR] [STACK TRACE] TypeError: Cannot read properties of undefined (reading 'yellow')
    at UX.warn (C:\Users\...\AppData\Local\sfdx\node_modules\sfdmu\node_modules\@salesforce\command\lib\ux.js:203:41)
    at Logger.log (C:\Users\...\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\components\common_components\logger.js:479:35)
    at MigrationJobTask._apiProgressCallback (C:\Users\...\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\job_models\migrationJobTask.js:1299:29)
    at BulkApiV2_0Engine.processCRUDApiBatchAsync (C:\Users\...\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\components\api_engines\bulkApiV2_0Engine.js:95:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async BulkApiV2_0Engine.processCRUDApiJobAsync (C:\Users\...\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\api_models\ApiEngineBase.js:127:33)
    at async BulkApiV2_0Engine.executeCRUD (C:\Users\...\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\api_models\ApiEngineBase.js:79:29)
    at async BulkApiV2_0Engine.executeCRUDMultithreaded (C:\Users\...\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\api_models\ApiEngineBase.js:86:20)
    at async ___updateData (C:\Users\...\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\job_models\migrationJobTask.js:816:37)
    at async MigrationJobTask.updateRecords (C:\Users\...\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\job_models\migrationJobTask.js:650:45)
    at async MigrationJob.updateRecordsAsync (C:\Users\...\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\job_models\migrationJob.js:303:43)
    at async RunCommand.executeJobAsync (C:\Users\...\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\commands_processors\runCommand.js:84:9)
    at async Function.execute (C:\Users\...\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\commands_processors\runCommandExecutor.js:41:13)
    at async Run.run (C:\Users\...\AppData\Local\sfdx\node_modules\sfdmu\lib\commands\sfdmu\run.js:20:9)
    at async Run._run (C:\Users\...\AppData\Local\sfdx\node_modules\sfdmu\node_modules\@salesforce\command\lib\sfdxCommand.js:81:40)
    at async Config.runCommand (C:\Users\...\AppData\Roaming\nvm\v16.13.0\node_modules\sfdx-cli\node_modules\@oclif\config\lib\config.js:173:24)
[09:24:58.367] Execution of the command sfdmu:run has been finished. Exit code 1 (COMMAND_UNEXPECTED_ERROR).
[09:24:58.368] Total time elapsed: 00h 01m 49s 985ms .

Last month this import working great and now it is not working and I don't understand why...

Thansk for the help

**Comment by hknokh** [comment]
Hello @lioram 
I think you use valuemapping.
To analyse the issue, I need:
 - your export.json + valuemapping.csv ( at least the rows of this file, that you quess that they may cause the issue). 
 -  which api name of the field it tried to map and failed ?
 -  what is the inital field value that it tried to replace with the mapped one ?

**Comment by lioram** [comment]
Thanks for the reply @hknokh 

Here is a sample of my export : 
"objects": [
    {
      "query": "SELECT all FROM PDFObj__c",
      "operation": "Upsert",
      "externalId":"Name"
    },
    {
      "query":"SELECT Id, Name, PDFObj__c$PDFObj__c FROM PDFObjView__c",
      "operation":"Upsert",
      "externalId":"Name"
    }


---
valuemapping.csv
Id,Name,Limit__c,MapCols__c,OrderByDesc__c,OrderBy__c,PDFObj__c,Presentation__c,ViewName__c,separator__c,soqlquery__c,IntegrationId__c,PDFObj__r.Name
a0bXXXXXXXX,XXXXX,,,false,,a0cD0000001SLdaIAG,valeurs séparées par un caractère,XXXXX,espace,Select XXX From XXX,,MTX - Facture banque
---
Here is the error log
[15:34:20.783] UPDATING THE TARGET STAGE 1 ...
[15:34:20.785] {PDFObj__c} [INFO] There are 55 skipped target updates, since no matching was found between the source and the target records by the given ExternalId key, or the data is the same.
[15:34:20.801] {PDFObjView__c} Number of records to Insert: 1947.
[15:34:20.813] {PDFObjView__c} The Insert API operation has been started using Bulk API V2.0.
[15:34:21.229] [Job# 7501q000009Uq7ZAAS:Insert] {PDFObjView__c} The job has been created. Uploading data ...
[15:34:22.3] [Batch# 7501q000009Uq7ZAAS:Insert] {PDFObjView__c} The batch has been created. Uploading data ...
[15:34:22.146] [Batch# 7501q000009Uq7ZAAS:Insert] {PDFObjView__c} The data has been uploaded. Processing ...
[15:34:37.669] [Batch# 7501q000009Uq7ZAAS:Insert] {PDFObjView__c} Processing ... 200 records processed, 67 records failed.
[15:34:42.554] [Batch# 7501q000009Uq7ZAAS:Insert] {PDFObjView__c} Processing ... 600 records processed, 467 records failed.
[15:34:47.711] [Batch# 7501q000009Uq7ZAAS:Insert] {PDFObjView__c} Processing ... 1000 records processed, 867 records failed.
[15:34:52.831] [Batch# 7501q000009Uq7ZAAS:Insert] {PDFObjView__c} Processing ... 1947 records processed, 1021 records failed.
[15:34:57.631][ERROR] Execution of the command was ABORTED due to unexpected error: Cannot read properties of undefined (reading 'yellow').
[15:34:57.632][ERROR] [STACK TRACE] TypeError: Cannot read properties of undefined (reading 'yellow')
    at UX.warn (C:\Users\xxx\AppData\Local\sfdx\node_modules\sfdmu\node_modules\@salesforce\command\lib\ux.js:203:41)
    at Logger.log (C:\Users\xxx\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\components\common_components\logger.js:479:35)

**Comment by hknokh** [comment]
Don't understand. Your file is not of the valuemapping.csv format. 
Do you really use value mapping feature?
When does this error occur?
What is the 'yellow'?

**Comment by lioram** [comment]
Hi @hknokh,

I'm sorry I don't usted any valuemapping file because I don't transform any fields.
I just export from the production and import to a sandbox.
The same script was working perfect last month that Why I don't understand what is happing and also I don't understand the yellow error...

**Comment by hknokh** [comment]
Hello @lioram 
OK. I can't reproduce it on my side, because it depends on your specific configuration. 
Generally it should be debugged on your side, I'm not sure that I will be able to fix it, but I will make my effort to invesigate again.  For now you can rollback to the working version you've used before.

**Comment by petter-eikeland** [comment]
Hi @hknokh,

It seems like one of my coworkers is experiencing the same issue

First she tried with SFDMU version 4.18.2. She then got the following error message:

```
[09:46:50.474] Execution of the command sfdmu:run has been started.
=== Loading and validating the export.json script ...
=== OBJECT SET #1 STARTED
Running Plugin version: 4.23.2
Running Add-On API version: 1.4.0
[09:46:50.494] Loading Core Add-On Module declarations ...
[09:46:50.713] Connecting to the product-catalog-data using SFDX force:org:display ...
[09:46:57.350] Successfully connected to the product-catalog-data.
Package script: /Users/user/BICX/src/product-catalog/product-catalog-data/export.json.
Source:         csvfile.
Target:         product-catalog-data.
=== Getting and analysing object metadata ...
[09:46:58.220] Retrieving metadata of the Account (Target) ...
[09:46:59.459] Retrieving metadata of the Contact (Target) ...
[09:47:00.372] Retrieving metadata of the Product2 (Target) ...
[09:47:01.54] Retrieving metadata of the ProductAttributeSet (Target) ...
[09:47:01.568] Retrieving metadata of the ProductAttributeSetProduct (Target) ...
[09:47:02.79] Retrieving metadata of the ProductAttribute (Target) ...
[09:47:02.596] Retrieving metadata of the Group (Target) ...
=== Preparing data migration job ...
[09:47:03.300] Building the migration strategy ...
Order of objects to query: ProductAttributeSet; Account; Contact; Product2; ProductAttributeSetProduct; ProductAttribute
Order of objects to delete: ProductAttribute; ProductAttributeSetProduct; Product2; Contact; Account; ProductAttributeSet
Order of objects to update: ProductAttributeSet; Account; Contact; Product2; ProductAttributeSetProduct; ProductAttribute
[09:47:03.308] Validation of the source CSV files ...
Command in progress... done

[09:47:03.344] [ERROR] Execution of the command has aborted due to unexpected error: Cannot read properties of undefined (reading 'yellow').
[09:47:03.350] [ERROR] [STACK TRACE] TypeError: Cannot read properties of undefined (reading 'yellow')
    at UX.warn (/Users/user/.local/share/sfdx/node_modules/sfdmu/node_modules/@salesforce/command/lib/ux.js:203:41)
    at Logger.log (/Users/user/.local/share/sfdx/node_modules/sfdmu/lib/modules/components/common_components/logger.js:351:58)
    at Logger.warn (/Users/user/.local/share/sfdx/node_modules/sfdmu/lib/modules/components/common_components/logger.js:402:18)
    at Common.abortWithPrompt (/Users/user/.local/share/sfdx/node_modules/sfdmu/lib/modules/components/common_components/common.js:519:26)
    at ___promptToAbort (/Users/user/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/job_models/migrationJob.js:628:35)
    at MigrationJob._validateAndRepairSourceCSVFiles (/Users/user/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/job_models/migrationJob.js:617:23)
    at async MigrationJob.processCSVFilesAsync (/Users/user/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/job_models/migrationJob.js:169:17)
    at async RunCommand.processCSVFilesAsync (/Users/user/.local/share/sfdx/node_modules/sfdmu/lib/modules/commands_processors/runCommand.js:90:9)
    at async RunCommandExecutor.execute (/Users/user/.local/share/sfdx/node_modules/sfdmu/lib/modules/commands_processors/runCommandExecutor.js:41:17)
    at async Run.run (/Users/user/.local/share/sfdx/node_modules/sfdmu/lib/commands/sfdmu/run.js:20:9)
    at async Run._run (/Users/user/.local/share/sfdx/node_modules/sfdmu/node_modules/@salesforce/command/lib/sfdxCommand.js:81:40)
    at async Config.runCommand (/Users/user/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@oclif/core/lib/config/config.js:272:25)
    at async run (/Users/user/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@oclif/core/lib/main.js:74:5)
[09:47:03.354] [ERROR] Execution of the command sfdmu:run has been completed. Exit code 1 (COMMAND_UNEXPECTED_ERROR).
[09:47:03.357] Total time elapsed: 00h 00m 12s 872ms .
```

We updated sfdmu & sfdx to versions 4.23.2 & 7.182.1, respectively and tried again --> Same error.
We are inserting Accounts, Contacts, Product Variations & Product Variation Parents with associated objects. I have attached the export.json and our corresponding csv files below. 

Now, if my coworker removes ProductAttributeSetProduct & ProductAttribute from the export.json (i.e. inserting only Account, Contact, Product2 & retrieveing ProductAttributeSet), the error goes away. When we readd the ProductAttributeSetProduct object, the error appears again. Perhaps its only related to that adding this object triggers a yellow SFDMU warning which again triggers the issue

The weird thing is that I am on the same sfdx & sfdmu version as her, and I do not experience the same issues.
FYI: We are both using SFDMU on Mac Os. 

[Account.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/10381120/Account.csv)
[Contact.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/10381121/Contact.csv)
[export.json.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/10381122/export.json.txt)
[Product2.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/10381123/Product2.csv)
[ProductAttribute.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/10381124/ProductAttribute.csv)
[ProductAttributeSet.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/10381125/ProductAttributeSet.csv)
[ProductAttributeSetProduct.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/10381126/ProductAttributeSetProduct.csv)

**Comment by petter-eikeland** [comment]
@hknokh Uninstalling SFDMU & reinstalling again did the trick. The error was related to the yellow Warning messages from SFDMU

**Comment by hknokh** [comment]
@petter-eikeland Thanks for the update.
The SFDX-CLI core libraries had some bugs.
Yesterday I've pushed the new version of the SFDMU  which includes the up-to-date lib dependencies.
And it's recommended to upgrade the Plugin.
It seems to me that the latest versions of the core SFDX libs work much more stable.
