### ISSUE TITLE
Unexpected error for objects not supporting aggregate functions

### ISSUE THREAD

**Issue by kevdo475** [forcedotcom/SFDX-Data-Move-Utility#46]
The following error is encountered when trying to Insert FeedItems. This is due to FeedItem not supporting aggregate functions such as Count().
https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_feeditem.htm

```
[STACK TRACE] MALFORMED_QUERY: 
SELECT COUNT(Id) CNT FROM FeedItem
             ^
ERROR at Row:1:Column:14
field Id does not support aggregate operator COUNT
    at HttpApi.getError (/.local/share/sfdx/node_modules/jsforce/lib/http-api.js:250:13)
    at /.local/share/sfdx/node_modules/jsforce/lib/http-api.js:95:22
    at tryCallOne (/.local/share/sfdx/node_modules/promise/lib/core.js:37:12)
    at /.local/share/sfdx/node_modules/promise/lib/core.js:123:15
    at flush (/.local/share/sfdx/node_modules/asap/raw.js:50:29)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Execution of the command sfdmu:run has been finished. Exit code 1 (COMMAND_UNEXPECTED_ERROR).
```

**Comment by hknokh** [comment]
Hello @kevdo475 
The issue should be fixed. Please re-check
