### ISSUE TITLE
[BUG]- Object Sets not recognized as part of the export.json format

### ISSUE THREAD

**Issue by hutchinsonn** [forcedotcom/SFDX-Data-Move-Utility#463]
**Describe the bug**
Using the standard ObjectSet export.json example (https://help.sfdmu.com/full-documentation/advanced-features/multiple-object-sets) results in an error that there are no objects defined in the export.json 

**To Reproduce**
Create an export.json with the template ObjectSet export.json file, and attempt a run job from any environment to another.

**Expected behavior**
Expected to utilize the ObjectSets functionality to create sub jobs in a single job file.

**export.json**
`  {
  "objectSets": [
    {
      "objects": [
        {
          "query": "SELECT Id FROM Account",
          "operation": "Readonly"
        },
        {
          "query": "SELECT Id FROM Opportunity",
          "operation": "Readonly"
        }
      ]
    },
    {
      "objects": [
        {
          "query": "SELECT Name FROM Account LIMIT 1",
          "operation": "Insert"
        }
      ]
    }
  ]
}`

**Log file**
`[15:40:46.562] {"Running Plugin version":"4.14.2"}
[15:40:46.564] {"Running Add-On Api version":"1.3.0"}

[15:40:46.565] Loading core Add-On declarations ...
[15:40:46.577][ERROR] Command initialization error: There are no objects defined to process..
[15:40:46.578][ERROR] [STACK TRACE] Error: There are no objects defined to process.
    at Script.setupAsync (/Users/nh/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/script_models/script.js:161:19)
    at async RunCommand.setupObjectSetAsync (/Users/nh/.local/share/sfdx/node_modules/sfdmu/lib/modules/commands_processors/runCommand.js:68:9)
    at async Function.execute (/Users/nh/.local/share/sfdx/node_modules/sfdmu/lib/modules/commands_processors/runCommandExecutor.js:38:17)
    at async Run.run (/Users/nh/.local/share/sfdx/node_modules/sfdmu/lib/commands/sfdmu/run.js:20:9)
    at async Run._run (/Users/nh/.local/share/sfdx/node_modules/@salesforce/command/lib/sfdxCommand.js:81:40)
    at async Config.runCommand (/Users/nh/.local/share/sfdx/client/7.149.1-3881a5a/node_modules/@oclif/config/lib/config.js:173:24)
    at async SfdxMain.run (/Users/nh/.local/share/sfdx/client/7.149.1-3881a5a/node_modules/@oclif/command/lib/main.js:27:9)
    at async SfdxMain._run (/Users/nh/.local/share/sfdx/client/7.149.1-3881a5a/node_modules/@oclif/command/lib/command.js:43:20)
    at async Object.run (/Users/nh/.local/share/sfdx/client/7.149.1-3881a5a/dist/cli.js:162:47)
[15:40:46.578] Execution of the command sfdmu:run has been finished. Exit code 2 (COMMAND_INITIALIZATION_ERROR).
[15:40:46.579] Total time elapsed: 00h 00m 00s 026ms .`

**_target.csv** file.
When you have an issue with failed rows, attach the dump of the **_target.csv** file containing the error messages (at least 1-2 relevant full rows).

**Comment by hutchinsonn** [comment]
Not a bug, user error.
Had to include an "objects" before the objectSet to get this to run.
![image](https://user-images.githubusercontent.com/34116797/167922258-aafcec7b-eb34-4a5b-b5b8-2d24d3b96217.png)

**Comment by hknokh** [comment]
@hutchinsonn 
It's fixed. Update and retry plz
