### ISSUE TITLE
[BUG]- "C:\Program Files\Salesforce CLI\bin\node.exe"' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by flow-drive-1878** [forcedotcom/SFDX-Data-Move-Utility#490]
**Describe the bug**
After the update of SFDX CLI to 7.163.0 (I'm not entirely sure of the previous version - I believe it was the previous version, however, I can confirm it works with SFDX CLI version 7.110.0) SFDMU Scripts do not run fully, and the following error is presented. This happens for existing and new scripts.

_[ERROR] Execution of the command was ABORTED due to unexpected error: Command failed: sfdx force:org:display --json --targetusername test-********@example.com
'"C:\Program Files\Salesforce CLI\bin\node.exe"' is not recognized as an internal or external command,
operable program or batch file_

**To Reproduce**
Describe steps to reproduce the behavior.
1. Update SFDX CLI to the latest version (7.163.0)
2. Run an SFDMU Script - this seems to affect all of them - a basic test version is attached for this.
3. The script fails to run, and the error below appears.

In this case, I'm uploading an Account via CSV to an org, using the command:
sfdx sfdmu:run --sourceusername csvfile --targetusername test-********@example.com --path ./data/SFDX-SFDMU-Error

**Expected behavior**
The script runs without error, and an Account is inserted into the target org - with the logs of SFDMU indicating it has worked correctly.

**export.json**
`{
    "objects":[
       {
          "query":"SELECT Name FROM Account",
          "operation":"Insert"
       }
    ]
 }`

**Log file**
`
[09:51:04.213] {"Running Plugin version":"4.15.1"}
[09:51:04.215] {"Running Add-On Api version":"1.3.0"}

[09:51:04.218] Loading core Add-On declarations ...
[09:51:04.428] Connecting to test-********@example.com using SFDX force:org:display ...
[09:51:04.544][ERROR] Execution of the command was ABORTED due to unexpected error: Command failed: sfdx force:org:display --json --targetusername test-********@example.com
'"C:\Program Files\Salesforce CLI\bin\node.exe"' is not recognized as an internal or external command,
operable program or batch file.
.
[09:51:04.545][ERROR] [STACK TRACE] Error: Command failed: sfdx force:org:display --json --targetusername test-********@example.com
'"C:\Program Files\Salesforce CLI\bin\node.exe"' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at Function.execSfdx (C:\Users\********\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\components\common_components\common.js:196:49)
    at ScriptOrg._setupConnection (C:\Users\********\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\script_models\scriptOrg.js:118:53)
    at ScriptOrg.setupAsync (C:\Users\********\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\script_models\scriptOrg.js:52:20)
    at Script.setupAsync (C:\Users\********\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\script_models\script.js:182:30)
    at async RunCommand.setupObjectSetAsync (C:\Users\********\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\commands_processors\runCommand.js:67:9)
    at async Function.execute (C:\Users\********\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\commands_processors\runCommandExecutor.js:37:17)
    at async Run.run (C:\Users\********\AppData\Local\sfdx\node_modules\sfdmu\lib\commands\sfdmu\run.js:20:9)
[09:51:04.546] Execution of the command sfdmu:run has been finished. Exit code 1 (COMMAND_UNEXPECTED_ERROR).
[09:51:04.547] Total time elapsed: 00h 00m 00s 337ms .`

**Comment by hknokh** [comment]
Hello

I think that that this is another bug with the SFDX CLI which causes backward incompability with the old plugins.  I've already shared this one:
https://github.com/forcedotcom/SFDX-Data-Move-Utility/issues/484
with the SFDX CLI team, please see the comment there.
For now please revert to the older version of the SFDX CLI
FYI: @mshanemc
