### ISSUE TITLE
[BUG] valid export.json with RecordTypeId throws error "extraneous input" 

### ISSUE THREAD

**Issue by kalius** [forcedotcom/SFDX-Data-Move-Utility#495]
**Describe the bug**
When there are two queries where one object is child of another and parent object query has RecordTypeId, child query has lookup field which is identical to parent object's dev name, there is an error thrown

`sfdx sfdmu:run --sourceusername org_Alias --targetusername csvfile --path DemoError2 
`
**To Reproduce**
Create two linked objects, where lookup field has same name as parent object dev name. Create recordtype on parent objects. No data is needed for error to be thrown.
Object 1: a__c (create record type)
Object 2: b__c (create a__c field lookup to a__c object)

**Expected behavior**
Export should finish without an error.

**export.json**
```
{
    "createTargetCSVFiles": true,
    "objects": [
		{
            "query": "select a__c from b__c",
            "operation": "Insert",
            "deleteOldData": false,
            "excluded": false
        },
        {
            "query": "select RecordTypeId from a__c",
            "operation": "Insert",
            "deleteOldData": false,
            "excluded": false
        }
    ]
}
```
**Log file**
[ERROR] Error during execution of the command: line 1:43 extraneous input 'FROM' expecting {GROUP, ABOVE, ABOVE_OR_BELOW, AT, BELOW, CATEGORY, DATA, END, OFFSET, ORDER, REFERENCE, SCOPE, TRACKING, THEN, TYPEOF, VIEW, VIEWSTAT, WHEN, SECURITY_ENFORCED, CALENDAR_MONTH, CALENDAR_QUARTER, CALENDAR_YEAR, DAY_IN_MONTH, DAY_IN_WEEK, DAY_IN_YEAR, DAY_ONLY, FISCAL_MONTH, FISCAL_QUARTER, FISCAL_YEAR, HOUR_IN_DAY, WEEK_IN_MONTH, WEEK_IN_YEAR, AVG, COUNT, COUNT_DISTINCT, MIN, MAX, SUM, DISTANCE, GEOLOCATION, FORMAT, TOLABEL, CONVERT_TIME_ZONE, CONVERT_CURRENCY, GROUPING, YESTERDAY, TODAY, TOMORROW, LAST_WEEK, THIS_WEEK, NEXT_WEEK, LAST_MONTH, THIS_MONTH, NEXT_MONTH, LAST_90_DAYS, NEXT_90_DAYS, THIS_QUARTER, LAST_QUARTER, NEXT_QUARTER, THIS_YEAR, LAST_YEAR, NEXT_YEAR, THIS_FISCAL_QUARTER, LAST_FISCAL_QUARTER, NEXT_FISCAL_QUARTER, THIS_FISCAL_YEAR, LAST_FISCAL_YEAR, NEXT_FISCAL_YEAR, NEXT_N_DAYS, LAST_N_DAYS, N_DAYS_AGO, NEXT_N_WEEKS, LAST_N_WEEKS, N_WEEKS_AGO, NEXT_N_MONTHS, LAST_N_MONTHS, N_MONTHS_AGO, NEXT_N_QUARTERS, LAST_N_QUARTERS, N_QUARTERS_AGO, NEXT_N_YEARS, LAST_N_YEARS, N_YEARS_AGO, NEXT_N_FISCAL_QUARTERS, LAST_N_FISCAL_QUARTERS, N_FISCAL_QUARTERS_AGO, NEXT_N_FISCAL_YEARS, LAST_N_FISCAL_YEARS, N_FISCAL_YEARS_AGO, ID}.

**Comment by hknokh** [comment]
This error returned from the Salesforce API as is.
- Check your query in the Developer Console.
- put here **complete** log file, I can look onto this.

**Comment by kalius** [comment]
I've checked the queries, they seem fine.

Complete log file:

[19:52:24.723] Execution of the command sfdmu:run has been started.

[19:52:24.737] LOADING AND VALIDATING THE PACKAGE SCRIPT ...

[19:52:24.742] OBJECT SET #1 STARTED

[19:52:24.760] {"Running Plugin version":"4.15.1"}
[19:52:24.763] {"Running Add-On Api version":"1.3.0"}

[19:52:24.773] Loading core Add-On declarations ...
[19:52:25.15] Connecting to dev using SFDX force:org:display ...
[19:52:27.852] Successfully connected to dev.
[19:52:28.250] {"SOURCE":"dev.","TARGET":"csvfile.","Package script":"/mnt/d/_dx projects/Gecko/templates/data/DemoError3/export.json."}

[19:52:28.254] GETTING AND ANALYSING OBJECTS METADATA ...
[19:52:28.256] Processing the sObject b__c ...
[19:52:28.258] Getting metadata for b__c (SOURCE)
[19:52:28.671] Processing the sObject a__c ...
[19:52:28.673] Getting metadata for a__c (SOURCE)
[19:52:29.42] Getting metadata for Group (SOURCE)
[19:52:29.379] Processing the sObject a__c ...
[19:52:29.385] Getting metadata for RecordType (SOURCE)
[19:52:32.255] The parent sobject RecordType for the lookup field a__c.RecordTypeId has been included into the process. The externalId is set to 'DeveloperName;NamespacePrefix;SobjectType'.
[19:52:32.259] Processing the sObject b__c ...

[19:52:32.287] PREPARING DATA MIGRATION JOB ...
[19:52:32.296] Building migration strategy ...
[19:52:32.303] {"Order of objects to retrieve data":"RecordType; a__c; b__c"}
[19:52:32.306] {"Order of objects to delete data":"b__c; a__c; RecordType"}
[19:52:32.312] {"Order of objects to update data":"RecordType; a__c; b__c"}
[19:52:32.318] Preparing has been finished.

[19:52:32.327] ANALYSING THE OVERALL DATA VOLUME ...
[19:52:32.532] {RecordType} Total amount of the SOURCE records should be retrieved by the object's SOQL query: 8
[19:52:32.709] {a__c} Total amount of the SOURCE records should be retrieved by the object's SOQL query: 0
[19:52:32.904] {b__c} Total amount of the SOURCE records should be retrieved by the object's SOQL query: 0

[19:52:32.912] PROCESSING ADD-ON EVENT HANDLERS ...
[19:52:32.916] No Add-On modules found to process.

[19:52:32.924] Ready to process the data.

[19:52:32.936] DELETING OLD DATA FROM THE TARGET ...
[19:52:32.941] {b__c} No records to delete.
[19:52:32.948] {a__c} No records to delete.
[19:52:32.952] {RecordType} No records to delete.
[19:52:32.956] Deleting data was skipped.

[19:52:32.968] RETRIEVING THE DATA STAGE 1 ...
[19:52:32.974] {RecordType} Retrieving the SOURCE data from Org (STAGE 1: all records) ...
[19:52:32.979] {RecordType} Query string: SELECT Id, $$DeveloperName$NamespacePrefix$SobjectType  FROM  RecordType.
[19:52:33.217] {RecordType} Retrieving the SOURCE data has been completed. Fetched 6 new records.
[19:52:33.222] {a__c} Retrieving the SOURCE data from Org (STAGE 1: all records) ...
[19:52:33.226] {a__c} Query string: SELECT Id, RecordTypeId, Name, RecordType.  FROM  a__c.
[19:52:33.251][ERROR] Error during execution of the command: line 1:43 extraneous input 'FROM' expecting {GROUP, ABOVE, ABOVE_OR_BELOW, AT, BELOW, CATEGORY, DATA, END, OFFSET, ORDER, REFERENCE, SCOPE, TRACKING, THEN, TYPEOF, VIEW, VIEWSTAT, WHEN, SECURITY_ENFORCED, CALENDAR_MONTH, CALENDAR_QUARTER, CALENDAR_YEAR, DAY_IN_MONTH, DAY_IN_WEEK, DAY_IN_YEAR, DAY_ONLY, FISCAL_MONTH, FISCAL_QUARTER, FISCAL_YEAR, HOUR_IN_DAY, WEEK_IN_MONTH, WEEK_IN_YEAR, AVG, COUNT, COUNT_DISTINCT, MIN, MAX, SUM, DISTANCE, GEOLOCATION, FORMAT, TOLABEL, CONVERT_TIME_ZONE, CONVERT_CURRENCY, GROUPING, YESTERDAY, TODAY, TOMORROW, LAST_WEEK, THIS_WEEK, NEXT_WEEK, LAST_MONTH, THIS_MONTH, NEXT_MONTH, LAST_90_DAYS, NEXT_90_DAYS, THIS_QUARTER, LAST_QUARTER, NEXT_QUARTER, THIS_YEAR, LAST_YEAR, NEXT_YEAR, THIS_FISCAL_QUARTER, LAST_FISCAL_QUARTER, NEXT_FISCAL_QUARTER, THIS_FISCAL_YEAR, LAST_FISCAL_YEAR, NEXT_FISCAL_YEAR, NEXT_N_DAYS, LAST_N_DAYS, N_DAYS_AGO, NEXT_N_WEEKS, LAST_N_WEEKS, N_WEEKS_AGO, NEXT_N_MONTHS, LAST_N_MONTHS, N_MONTHS_AGO, NEXT_N_QUARTERS, LAST_N_QUARTERS, N_QUARTERS_AGO, NEXT_N_YEARS, LAST_N_YEARS, N_YEARS_AGO, NEXT_N_FISCAL_QUARTERS, LAST_N_FISCAL_QUARTERS, N_FISCAL_QUARTERS_AGO, NEXT_N_FISCAL_YEARS, LAST_N_FISCAL_YEARS, N_FISCAL_YEARS_AGO, ID}.
[19:52:33.254][ERROR] [STACK TRACE] Error: line 1:43 extraneous input 'FROM' expecting {GROUP, ABOVE, ABOVE_OR_BELOW, AT, BELOW, CATEGORY, DATA, END, OFFSET, ORDER, REFERENCE, SCOPE, TRACKING, THEN, TYPEOF, VIEW, VIEWSTAT, WHEN, SECURITY_ENFORCED, CALENDAR_MONTH, CALENDAR_QUARTER, CALENDAR_YEAR, DAY_IN_MONTH, DAY_IN_WEEK, DAY_IN_YEAR, DAY_ONLY, FISCAL_MONTH, FISCAL_QUARTER, FISCAL_YEAR, HOUR_IN_DAY, WEEK_IN_MONTH, WEEK_IN_YEAR, AVG, COUNT, COUNT_DISTINCT, MIN, MAX, SUM, DISTANCE, GEOLOCATION, FORMAT, TOLABEL, CONVERT_TIME_ZONE, CONVERT_CURRENCY, GROUPING, YESTERDAY, TODAY, TOMORROW, LAST_WEEK, THIS_WEEK, NEXT_WEEK, LAST_MONTH, THIS_MONTH, NEXT_MONTH, LAST_90_DAYS, NEXT_90_DAYS, THIS_QUARTER, LAST_QUARTER, NEXT_QUARTER, THIS_YEAR, LAST_YEAR, NEXT_YEAR, THIS_FISCAL_QUARTER, LAST_FISCAL_QUARTER, NEXT_FISCAL_QUARTER, THIS_FISCAL_YEAR, LAST_FISCAL_YEAR, NEXT_FISCAL_YEAR, NEXT_N_DAYS, LAST_N_DAYS, N_DAYS_AGO, NEXT_N_WEEKS, LAST_N_WEEKS, N_WEEKS_AGO, NEXT_N_MONTHS, LAST_N_MONTHS, N_MONTHS_AGO, NEXT_N_QUARTERS, LAST_N_QUARTERS, N_QUARTERS_AGO, NEXT_N_YEARS, LAST_N_YEARS, N_YEARS_AGO, NEXT_N_FISCAL_QUARTERS, LAST_N_FISCAL_QUARTERS, N_FISCAL_QUARTERS_AGO, NEXT_N_FISCAL_YEARS, LAST_N_FISCAL_YEARS, N_FISCAL_YEARS_AGO, ID}
    at Sfdx.queryOrgOrCsvAsync (/home/simon/.local/share/sfdx/node_modules/sfdmu/lib/modules/components/common_components/sfdx.js:123:19)
    at MigrationJobTask.retrieveRecords (/home/simon/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/job_models/migrationJobTask.js:551:42)
    at MigrationJob.retrieveRecordsAsync (/home/simon/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/job_models/migrationJob.js:210:36)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RunCommand.executeJobAsync (/home/simon/.local/share/sfdx/node_modules/sfdmu/lib/modules/commands_processors/runCommand.js:100:9)
    at async Function.execute (/home/simon/.local/share/sfdx/node_modules/sfdmu/lib/modules/commands_processors/runCommandExecutor.js:42:17)
    at async Run.run (/home/simon/.local/share/sfdx/node_modules/sfdmu/lib/commands/sfdmu/run.js:20:9)
    at async Run._run (/home/simon/.local/share/sfdx/node_modules/sfdmu/node_modules/@salesforce/command/lib/sfdxCommand.js:81:40)
    at async Config.runCommand (/home/simon/sfdx/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/config/config.js:272:25)
[19:52:33.258] Execution of the command sfdmu:run has been finished. Exit code 4 (COMMAND_EXECUTION_ERROR).
[19:52:33.264] Total time elapsed: 00h 00m 08s 518ms .

**Comment by hknokh** [comment]
hi @kalius 
This issue has been fixed.
please update and retry

**Comment by kalius** [comment]
@hknokh cool, it works now. Thanks for quick response.
