### ISSUE TITLE
[BUG]-Migrating related records, tool does not filter children by the parent 

### ISSUE THREAD

**Issue by SKN536** [forcedotcom/SFDX-Data-Move-Utility#543]
**Describe the bug**
When migrating related records, the child records are not filtered by the parent records and require additional filter. This causes an issues specially with polymorphic fields which prevents filtering by custom fields.

**Error Message**
```
[2022-12-28  21:07:11.589] {Attachment} Query string: SELECT Id, Body, ContentType, Description, Name, ParentId, Parent.Id, Parent.Subject  FROM  Attachment WHERE Parent.Type = 'EmailMessage'.
[2022-12-28  21:07:12.082] [ERROR] Error during execution of the command: exceeded 100000 distinct ids.
[2022-12-28  21:07:12.088] [STACK TRACE] Error: exceeded 100000 distinct ids
    at Sfdx.queryOrgOrCsvAsync (C:\Users\snallac\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\components\common_components\sfdx.js:124:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MigrationJobTask._retrieveFilteredRecords (C:\Users\snallac\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\job_models\migrationJobTask.js:1473:38)
    at async MigrationJobTask.retrieveRecords (C:\Users\snallac\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\job_models\migrationJobTask.js:570:35)
    at async MigrationJob.retrieveRecordsAsync (C:\Users\snallac\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\job_models\migrationJob.js:210:25)
    at async RunCommand.executeJobAsync (C:\Users\snallac\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\commands_processors\runCommand.js:100:9)
    at async RunCommandExecutor.execute (C:\Users\snallac\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\commands_processors\runCommandExecutor.js:42:17)
    at async Run.run (C:\Users\snallac\AppData\Local\sfdx\node_modules\sfdmu\lib\commands\sfdmu\run.js:20:9)
    at async Run._run (C:\Users\snallac\AppData\Local\sfdx\node_modules\@salesforce\command\lib\sfdxCommand.js:81:40)
    at async Config.runCommand (C:\Users\snallac\AppData\Local\sfdx\client\7.181.1-05b8719\node_modules\@oclif\core\lib\config\config.js:272:25)
[2022-12-28  21:07:12.093] Execution of the command sfdmu:run has been finished. Exit code 4 (COMMAND_EXECUTION_ERROR).
```

**To Reproduce**
Run the below export.json and notice that the child object fails as it hits the SF limit even when the master is restricted to just one record. Note this requires a large set of records to be present in the org.

**Expected behavior**
For all child records, restrict the querying to only the children associated to the parent records.

**export.json**
```
{
    "objects": [
        {
            "query": "Select Id, FromAddress, FromName, ToAddress, CcAddress, BccAddress, Incoming, MessageDate, Subject, Headers, TextBody, HtmlBody, CreatedDate, LastModifiedById, LastModifiedDate, RelatedToId$Case from EmailMessage where RelatedToId in (Select Id from Case where x18_Character_Case_Id__c = '5004z00001hDOKCAA4' )",
            "operation": "Insert",
            "master": true,
            "deleteOldData": false,
        },
        {
            "query": "SELECT Id, Body, ContentType, Description, Name, ParentId$EmailMessage From Attachment WHERE Parent.Type='EmailMessage'",
            "operation": "Insert",
            "master": false,
            "deleteOldData": false
        },
        {
            "query": "SELECT Id, X18_Character_Case_ID__c from Case where X18_Character_Case_ID__c = '5004z00001hDOKCAA4'",
            "operation": "Readonly",
            "externalId": "X18_Character_Case_ID__c"
        },
        {
            "query": "SELECT Id, X18_Character_User_ID__c from User",
            "operation": "Readonly",
            "externalId": "X18_Character_User_ID__c"
        }
    ],
    "promptOnMissingParentObjects": false,
}
```

**Comment by hknokh** [comment]
@SKN536 

It's not a bug, so this issue has been converted into QUESTION.

This is my sample export.json (similar to yours but with one difference which pointed below):

```json
{
	"objects": [
		{
			"operation": "Insert",
			"deleteOldData": true,
			"master":true,
			"query": "SELECT Id, Name, Phone, OwnerId, RecordTypeId from Account WHERE Name IN ('ACC_10000', 'ACC_10001')"
		},
		{
          "operation": "Insert",
		  "deleteOldData": true,
          "query": "Select Id, FromAddress, FromName, ToAddress, CcAddress, BccAddress, Incoming, MessageDate, Subject, Headers, TextBody, HtmlBody, CreatedDate, LastModifiedById, LastModifiedDate, RelatedToId$Account from EmailMessage where RelatedToId IN (SELECT Id from Account WHERE Name IN ('ACC_10000', 'ACC_10001'))",
          "master": false
		},
		{
          "operation": "Insert",
          "query": "SELECT Id, Body, ContentType, Description, Name, ParentId$EmailMessage From Attachment ",
          "master": false
		}
	],
	"promptOnMissingParentObjects": false
}
```

And this is the query string to Attachment it generated (restricted by the parent emails):
```bash
[2022-12-29  11:57:43.986] {Attachment} Query string: SELECT Id, Body, ContentType, Description, Name, ParentId, Parent.Id, Parent.Subject  FROM  Attachment WHERE ParentId IN ('02s8d00000FicjaAAB').
```

You dont need to restrict the Attachment records with "WHERE Parent.Type = 'EmailMessage'" since it's a slave sObject (master=false) and you already defined EmailMessage as a parent object with a polymorphic syntax (ParentId$EmailMessage). So the SFDMU understand by itself how to filter Attachments by EmailMessages.

Some brief  information about master/slave modes. You should consider these in your export.json.
- By default all sObjects are in master mode.
- Master object's records are always limited by query string clauses are used (WHERE/LIMIT).
- Slave object's records are mostly filtered by the it's parent objects. If many parent objects are there, the final records set contains summarized set of child records filtered by ALL parent parent objects.
The SFDMU contains logic to reduce number of queried records as much as possible to prevent extra cost of resources, but it should understand what you want to get by your export.json and the job  indeed should be configured correctly.
- **And very important, which caused your issue:** if the slave query is limited like yours: "WHERE Parent.Type = 'EmailMessage'", it is built to perform **2 queries**:
- - SELECT bla-bla-bla FROM Attachment WHERE ParentId IN (LIST_OF_EMAIL_MESSAGE_IDS) - it's internally constructed filtered query
- - SELECT bla-bla-bla FROM Attachment WHERE Parent.Type = 'EmailMessage' - it's your **original query string** whic selects all email attachments.
So in your case it because if you restrict Attachments, you will finally get ALL attachments for the reason I said above.

I will think abut to review the logic, maybe will change it to a single query:
SELECT bla-bla-bla FROM Attachment WHERE (Parent.Type = 'EmailMessage') AND (ParentId IN (LIST_OF_EMAIL_MESSAGE_IDS))
- but I am currently only putting it into the roadmap for future releases. I need to think what to do with this, because it's very serios update, requires a lot of regression tests on the live product already used by huge number of people.

For now remove WHERE clause from Attachment object.

**Comment by hknokh** [comment]
@SKN536 
After reviewing this again I decided finally, that it's important to change the logic of retrieving child objects as I mentioned in the above post to include the original WHERE clause using AND logic.
It's the correct behavior because the user put WHERE to the object telling, that he definitely wants to limit records, so it's unreasonable to add extra records by our own.
So this improvement is added since v4.22.0.
I did some necessary regression tests and seems that it didn't break the overall process.
Now you can add WHERE Parent.Type = 'EmailMessage' into the query of Atachment.
Please let me know if you have any further questions.
Thx

**Comment by ElizabethJHodges** [comment]
I have the same issue. I am new to SFDMU. 
My export JSON looks like this: {
    "objects": [
        {
            "query": "SELECT Id, TechIDCapinfo__c, TechIDSAPCC__c, Tech_ZendeskID__c, createable_true FROM Account WHERE TechToExportFlag__c = true",
            "operation": "Upsert",
            "master":true,
            "externalId": "TechIDCapinfo__c;TechIDSAPCC__c;Tech_ZendeskID__c"
        },
        {
            "query": "SELECT Id, creatable_true FROM Case",
            "operation": "Upsert",
            "master":false,
            "externalId": "CaseNumber"
        },
        {
            "query": "SELECT Id, creatable_true FROM Opportunity",
            "operation": "Upsert",
            "master":false,
            "externalId": "Name"
        }
    ]
}

However, it is hitting salesforce limits on the Opportunites, and existing before getting to stage 2. I have flagged 3837 accounts for export using the field TechToExportFlag__c. I want to export only the child opportunities and cases for these accounts. 

However, the output is this : 
 [10:45:33.825] Preparing of the data migration job has been completed.
 [10:45:33.825] newLine
 ANALYSING DATA...
 [10:45:33.897] {Individual} The original query string of this object is returning 0 records from the Source org.
 [10:45:34.138] {Individual} The original query string of this object is returning 0 records from the Target org.
 [10:45:42.459] {Contact} The original query string of this object is returning 9164647 records from the Source org.
 [10:45:43.355] {Contact} The original query string of this object is returning 697315 records from the Target org.
 [10:45:57.106] {Account} The original query string of this object is returning 3837 records from the Source org.
 [10:45:57.895] {Case} The original query string of this object is returning 506677 records from the Source org.
 [10:45:57.986] {Case} The original query string of this object is returning 0 records from the Target org.
 [10:46:00.354] {Opportunity} The original query string of this object is returning 2970239 records from the Source org.
 [10:46:00.734] {Opportunity} The original query string of this object is returning 375136 records from the Target org.
 [10:46:00.736] newLine
TRIGGERING ADD-ON EVENTS ...
 [10:46:00.738] No Add-On modules found to run.
 [10:46:00.739] newLine
 [10:46:00.740] Ready to process the data.
 [10:46:00.741] newLine
 DELETING OLD DATA FROM THE TARGET ...
 [10:46:00.744] {Opportunity} No records to delete.
 [10:46:00.745] {Case} No records to delete.
 [10:46:00.746] {Account} No records to delete.
 [10:46:00.746] {Contact} No records to delete.
 [10:46:00.747] {Individual} No records to delete.
 [10:46:00.748] Deleting data was skipped.
 [10:46:00.749] newLine
 SOURCE:
 =============
 [10:46:00.751] newLine
 FETCHING THE DATA (STAGE 1) ...
 [10:46:00.753] {Account} Fetching the Source data from Org (STAGE 1: all records) ...
 [10:46:00.753] {Account} Query string: SELECT Id, TechIDCapinfo__c, TechIDSAPCC__c, Tech_ZendeskID__c, $$TechIDCapinfo__c$TechIDSAPCC__c$Tech_ZendeskID__c, IsPersonAccount, IsDeleted, Name, LastName, FirstName, Salutation, Type, ParentId, BillingStreet, BillingCity, BillingState, BillingP... FROM  Account WHERE TechToExportFlag__c = true.
 [10:46:00.763] {Account} Using REST API to retrieve the data ...
 [10:46:16.891] In progress... Completed 2001 records.
 [10:46:17.746] In progress... Completed 3837 records.
 [10:46:17.836] {Account} Data retrieval (Source) has been completed. Got 3837 new records.
 [10:46:17.837] {Case} Fetching the Source data from Org (STAGE 1: all records) ...
 [10:46:17.838] {Case} Query string: SELECT Id, CaseNumber  FROM  Case.
 [10:46:17.838] {Case} Using Bulk API Query to retrieve the data ...
 [10:47:14.137] In progress... Completed 2001 records.
... <I CUT OUT MANY LINES>
 [10:47:15.689] In progress... Completed 506678 records.
 [10:47:16.186] {Case} Data retrieval (Source) has been completed. Got 506678 new records.
 [10:47:16.188] {Opportunity} Fetching the Source data from Org (STAGE 1: all records) ...
 [10:47:16.188] {Opportunity} Query string: SELECT Id, Name  FROM  Opportunity.
 [10:47:16.189] {Opportunity} Using Bulk API Query to retrieve the data ...
 [10:49:18.912] In progress... Completed 2001 records.
.... ... <I CUT OUT MANY LINES>
 [10:49:23.62] In progress... Completed 1000001 records.
Then it just dies.
