### ISSUE TITLE
[ERROR] "Cannot read property 'toString' of undefined" encountered when using the 'Add' operation

### ISSUE THREAD

**Issue by kevdo475** [forcedotcom/SFDX-Data-Move-Utility#56]
If the `"operation": "Add"` is used, the following error is encountered.
```
ERROR] Execution of the command was ABORTED due to unexpected error: Cannot read property 'toString' of undefined.
[STACK TRACE] TypeError: Cannot read property 'toString' of undefined
    at Function.getStrOperation (/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/script_models/scriptObject.js:268:51)
    at TaskData.getTargetCSVFilename (/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/common_models/helpers_classes.js:47:72)
    at ___writeToTargetCSVFile (/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/job_models/migrationJobTask.js:765:67)
    at MigrationJobTask.updateRecords (/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/job_models/migrationJobTask.js:513:23)
```
While debugging, it looks like there's no enum value in `statics.OPERATION`. 
If run with `"operation": "Upsert"`, `operation` has the correct value of 2.

**Comment by hknokh** [comment]
Hello @kevdo475 
Sorry for the confusing....
The Add / Merge operators were removed a lot of versions ago and I forgot to update the documentation. I updated the WIKI.
