### ISSUE TITLE
[BUG]-'"C:\Program Files\Salesforce CLI\bin\node.exe"' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by shamina-comf** [forcedotcom/SFDX-Data-Move-Utility#583]
**Describe the bug**
'"C:\Program Files\Salesforce CLI\bin\node.exe"' is not recognized as an internal or external command, operable program or batch file.
error is thrown when running the command for export from source to target org

Versions
 Plugin version: sfdmu v4.26.10
 
sfdx-cli/7.192.2 
win32-x64 
node-v18.14.1

**To Reproduce**
$ sfdx sfdmu:run --sourceusername SOURCE_ORG --targetusername TARGET_ORG --path "path/to/export"

See logs below
```
[17:11:46.624] Execution of the command sfdmu:run has been started.
=== Loading and validating the export.json script ...
=== OBJECT SET #1 STARTED
Running Plugin version: 4.26.10
Running Add-On API version: 1.5.0
[17:11:46.701] Loading Core Add-On Module declarations ...
[17:11:46.791] Connecting to the SOURCE_ORG using SFDX force:org:display ...
'"C:\Program Files\Salesforce CLI\bin\node.exe"' is not recognized as an internal or external command,
operable program or batch file.
Command in progress... done

[17:11:46.940] [ERROR] Execution of the command has aborted due to unexpected error: Command failed: sfdx force:org:display --json --targetusername TARGET_ORG
'"C:\Program Files\Salesforce CLI\bin\node.exe"' is not recognized as an internal or external command,
operable program or batch file.
.
[17:11:46.951] [ERROR] [STACK TRACE] Error: Command failed: sfdx force:org:display --json --targetusername TARGET_ORG
'"C:\Program Files\Salesforce CLI\bin\node.exe"' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at Common.execSfdx (C:\Users\XXX\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\components\common_components\common.js:196:49)
    at ScriptOrg._setupConnection (C:\Users\XXX\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\script_models\scriptOrg.js:118:53)
    at ScriptOrg.setupAsync (C:\Users\XXX\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\script_models\scriptOrg.js:52:20)
    at Script.setupAsync (C:\Users\XXX\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\script_models\script.js:209:30)
    at async RunCommand.setupObjectSetAsync (C:\Users\XXX\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\commands_processors\runCommand.js:69:9)
    at async RunCommandExecutor.execute (C:\Users\XXX\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\commands_processors\runCommandExecutor.js:39:17)
    at async Run.run (C:\Users\XXX\AppData\Local\sfdx\node_modules\sfdmu\lib\commands\sfdmu\run.js:20:9)
[17:11:46.960] [ERROR] Execution of the command sfdmu:run has been completed. Exit code 1 (COMMAND_UNEXPECTED_ERROR).
[17:11:46.963] Total time elapsed: 00h 00m 00s 319ms .
```
**Expected behavior**
export should run 

**export.json**
```
{
    "objects": [
        {
            "query": "SELECT Id, Name FROM Account",
            "operation": "Upsert",
            "externalId": "Name"
        }
    ]
}
```
**Log file**
```
 [17:11:46.624] Execution of the command sfdmu:run has been started.

 LOADING AND VALIDATING THE EXPORT.JSON SCRIPT ...

 OBJECT SET #1 STARTED

 {
   "Running Plugin version": "4.26.10"
}
 {
   "Running Add-On API version": "1.5.0"
}

 [17:11:46.701] Loading Core Add-On Module declarations ...
 [17:11:46.791] Connecting to the SOURCE_ORG using SFDX force:org:display ...

 [17:11:46.940] [ERROR] Execution of the command has aborted due to unexpected error: Command failed: sfdx force:org:display --json --targetusername SOURCE_ORG
'"C:\Program Files\Salesforce CLI\bin\node.exe"' is not recognized as an internal or external command,
operable program or batch file.
.
 [17:11:46.951] [ERROR] [STACK TRACE] Error: Command failed: sfdx force:org:display --json --targetusername SOURCE_ORG
'"C:\Program Files\Salesforce CLI\bin\node.exe"' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at Common.execSfdx (C:\Users\XXX\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\components\common_components\common.js:196:49)
    at ScriptOrg._setupConnection (C:\Users\XXX\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\script_models\scriptOrg.js:118:53)
    at ScriptOrg.setupAsync (C:\Users\XXX\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\script_models\scriptOrg.js:52:20)
    at Script.setupAsync (C:\Users\XXX\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\script_models\script.js:209:30)
    at async RunCommand.setupObjectSetAsync (C:\Users\XXX\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\commands_processors\runCommand.js:69:9)
    at async RunCommandExecutor.execute (C:\Users\XXX\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\commands_processors\runCommandExecutor.js:39:17)
    at async Run.run (C:\Users\XXX\AppData\Local\sfdx\node_modules\sfdmu\lib\commands\sfdmu\run.js:20:9)
 [17:11:46.960] [ERROR] Execution of the command sfdmu:run has been completed. Exit code 1 (COMMAND_UNEXPECTED_ERROR).
 [17:11:46.963] Total time elapsed: 00h 00m 00s 319ms .
```

**_target.csv** file.
n/a

**Comment by hknokh** [comment]
Hello,

Thank you for reaching out to me.

Unfortunately, I was not able to reproduce the issue you are experiencing on my end. Based on the specific configuration of your environment and the data you are trying to migrate, it seems likely that the issue may be unique to your setup.

For your reference, we recommend reviewing our guide on [how to debug](https://help.sfdmu.com/plugin-basics/basic-usage/debugging) the plugin locally, which may help you diagnose and address the issue.

Additionally, please ensure that you have the latest version of Node.js and SFDX-CLI installed on your local system, as this may be the cause of the issue you are experiencing.

Thank you for your understanding.

Best regards,
I'm here to help.
