### ISSUE TITLE
[FEATURE-REQUEST] Need support for sf cli commands instead of sfdx for gettting auth details

### ISSUE THREAD

**Issue by Shubhamkumarck** [forcedotcom/SFDX-Data-Move-Utility#596]
**Describe the bug**

As we must be aware that SF has deprecated the sfdx commands so can we shift the sfdx force:org:display to sf org display, As we have shifted all other pipeline scripts to use sf commands but this plugin is throwing an error as below

[06:10:41.4] Execution of the command sfdmu:run has been started.

[13](https://github.com/BridgePoint-Financial/CloudKaptan/actions/runs/4933695291/jobs/8817905486#step:10:14)=== Loading and validating the export.json script ...

[14](https://github.com/BridgePoint-Financial/CloudKaptan/actions/runs/4933695291/jobs/8817905486#step:10:15)=== OBJECT SET #1 STARTED

[15](https://github.com/BridgePoint-Financial/CloudKaptan/actions/runs/4933695291/jobs/8817905486#step:10:16)Running Plugin version: 4.26.13

[16](https://github.com/BridgePoint-Financial/CloudKaptan/actions/runs/4933695291/jobs/8817905486#step:10:17)Running Add-On API version: 1.5.0

[17](https://github.com/BridgePoint-Financial/CloudKaptan/actions/runs/4933695291/jobs/8817905486#step:10:18)[06:10:41.24] Loading Core Add-On Module declarations ...

[18](https://github.com/BridgePoint-Financial/CloudKaptan/actions/runs/4933695291/jobs/8817905486#step:10:19)[06:10:41.443] Connecting to the UAT using SFDX force:org:display ...

[19](https://github.com/BridgePoint-Financial/CloudKaptan/actions/runs/4933695291/jobs/8817905486#step:10:20)

[20](https://github.com/BridgePoint-Financial/CloudKaptan/actions/runs/4933695291/jobs/8817905486#step:10:21)Error: 6:10:41.458] [ERROR] Execution of the command has aborted due to unexpected error: Command failed: sfdx force:org:display --json --targetusername UAT

[21](https://github.com/BridgePoint-Financial/CloudKaptan/actions/runs/4933695291/jobs/8817905486#step:10:22)/bin/sh: 1: sfdx: not found

[22](https://github.com/BridgePoint-Financial/CloudKaptan/actions/runs/4933695291/jobs/8817905486#step:10:23).

[23](https://github.com/BridgePoint-Financial/CloudKaptan/actions/runs/4933695291/jobs/8817905486#step:10:24)Error: 6:10:41.461] [ERROR] [STACK TRACE] Error: Command failed: sfdx force:org:display --json --targetusername UAT

[24](https://github.com/BridgePoint-Financial/CloudKaptan/actions/runs/4933695291/jobs/8817905486#step:10:25)/bin/sh: 1: sfdx: not found

[25](https://github.com/BridgePoint-Financial/CloudKaptan/actions/runs/4933695291/jobs/8817905486#step:10:26)

[26](https://github.com/BridgePoint-Financial/CloudKaptan/actions/runs/4933695291/jobs/8817905486#step:10:27)    at checkExecSyncError (node:child_process:885:11)

[27](https://github.com/BridgePoint-Financial/CloudKaptan/actions/runs/4933695291/jobs/8817905486#step:10:28)    at execSync (node:child_process:957:15)

[28](https://github.com/BridgePoint-Financial/CloudKaptan/actions/runs/4933695291/jobs/8817905486#step:10:29)    at Common.execSfdx (/root/.local/share/sf/node_modules/sfdmu/lib/modules/components/common_components/common.js:196:49)

[29](https://github.com/BridgePoint-Financial/CloudKaptan/actions/runs/4933695291/jobs/8817905486#step:10:30)    at ScriptOrg._setupConnection (/root/.local/share/sf/node_modules/sfdmu/lib/modules/models/script_models/scriptOrg.js:118:53)

[30](https://github.com/BridgePoint-Financial/CloudKaptan/actions/runs/4933695291/jobs/8817905486#step:10:31)    at ScriptOrg.setupAsync (/root/.local/share/sf/node_modules/sfdmu/lib/modules/models/script_models/scriptOrg.js:52:20)

[31](https://github.com/BridgePoint-Financial/CloudKaptan/actions/runs/4933695291/jobs/8817905486#step:10:32)    at Script.setupAsync (/root/.local/share/sf/node_modules/sfdmu/lib/modules/models/script_models/script.js:210:30)

[32](https://github.com/BridgePoint-Financial/CloudKaptan/actions/runs/4933695291/jobs/8817905486#step:10:33)    at async RunCommand.setupObjectSetAsync (/root/.local/share/sf/node_modules/sfdmu/lib/modules/commands_processors/runCommand.js:69:9)

[33](https://github.com/BridgePoint-Financial/CloudKaptan/actions/runs/4933695291/jobs/8817905486#step:10:34)    at async RunCommandExecutor.execute (/root/.local/share/sf/node_modules/sfdmu/lib/modules/commands_processors/runCommandExecutor.js:39:17)

[34](https://github.com/BridgePoint-Financial/CloudKaptan/actions/runs/4933695291/jobs/8817905486#step:10:35)    at async Run.run (/root/.local/share/sf/node_modules/sfdmu/lib/commands/sfdmu/run.js:20:9)

[35](https://github.com/BridgePoint-Financial/CloudKaptan/actions/runs/4933695291/jobs/8817905486#step:10:36)Error: 6:10:41.461] [ERROR] Execution of the command sfdmu:run has been completed. Exit code 1 (COMMAND_UNEXPECTED_ERROR). 

**To Reproduce**
if we just try to import the plugin using sf commands instead of sfdx, it will throw this error.

**Expected behavior**
It should be able to fetch authorization details using SF command as well.

**export.json**
Attach your **export.json** file

**Log file**
Attach your full **.log** file.

**_target.csv** file.
When you have an issue with failed rows, attach the dump of the **_target.csv** file containing the error messages (at least 1-2 relevant full rows).

**Comment by hknokh2** [comment]
Hello,
Thank you for contacting me.
I've added a new command flag called --usesf to address your case. This flag forces the plugin to use SF-CLI commands instead of deprecated sfdx commands (e.g., sf org display instead of sfdx force:org:display).
Please refer to the documentation at:
https://help.sfdmu.com/running#available-command-flags
Please update the plugin and try again.
Cheers.

**Comment by hknokh** [comment]
Hello,
I hope the issue has been resolved for you. I'm closing it for now. Please let me know if you have any further questions.
Regards.
