### ISSUE TITLE
[QUESTION] - Meaning of sObject type 'Organization' is not supported..

### ISSUE THREAD

**Issue by wisutton** [forcedotcom/SFDX-Data-Move-Utility#601]
I have attempted to run SFDMU and received the below error (stack trace partially redacted). I am using an export.json file that works for someone else and I have confirmed that I am authenticated to MyOrg in SFDX. I am not sure what this error could mean other than an authentication issue but I believe I have ruled this out.

I note that the plugin runs `sfdx force:org:display` as per the logs, then prints the error output. I have run this command and did not receive an error.

```
PS ~\SFDMU Debugging> sfdx sfdmu:run --sourceusername MyOrg --targetusername csvfile
[18:07:08.358] Execution of the command sfdmu:run has been started.
=== Loading and validating the export.json script ...
=== OBJECT SET #1 STARTED
Running Plugin version: 4.27.0
Running Add-On API version: 1.5.0
[18:07:08.387] Loading Core Add-On Module declarations ...
[18:07:08.459] Connecting to the MyOrg using SFDX force:org:display ...
Command in progress... done

[18:07:14.544] [ERROR] Execution of the command has aborted due to unexpected error: sObject type 'Organization' is not supported..
[18:07:14.555] [ERROR] [STACK TRACE] INVALID_TYPE: sObject type 'Organization' is not supported.
at HttpApi.getError (C:\Users\wisutton\AppData\Local\sfdx\node_modules\jsforce\lib\http-api.js:250:13)
    at sfdx\node_modules\jsforce\lib\http-api.js:95:22
    at tryCallOne (sfdx\node_modules\promise\lib\core.js:37:12)
    at sfdx\node_modules\promise\lib\core.js:123:15
    at flush (sfdx\node_modules\asap\raw.js:50:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
[18:07:14.559] [ERROR] Execution of the command sfdmu:run has been completed. Exit code 1 (COMMAND_UNEXPECTED_ERROR).
[18:07:14.562] Total time elapsed: 00h 00m 06s 189ms .

PS ~\SFDMU Debugging>

```

**Comment by hknokh2** [comment]
Hello,

Thank you for reaching out to me. The tool needs to determine the type of organization it is working with, so it queries the object Organization using the SOQL "SELECT OrganizationType, IsSandbox FROM Organization LIMIT 1" for that purpose. Please ensure that you have the appropriate permissions on that object in order to work with SFDMU.

Regards

**Comment by hknokh** [comment]
I'm putting this case to 'in progress'

**Comment by hknokh** [comment]
Hello,
I hope the issue has been resolved for you. I'm closing it for now. Please let me know if you have any further questions.
Regards.
