### ISSUE TITLE
[Bug] Trying to export about 500k Attachments records but getting an error 'Invalid string length'

### ISSUE THREAD

**Issue by tajanePrajwal** [forcedotcom/SFDX-Data-Move-Utility#628]
I am looking to export EmailMessage Attachments. we have huge count of Attachment records about 500K 
We are unable to export the Attachments and facing the issue .

Below is the export.Json file.
{
    "objects": [
        {
            "operation": "Insert",
            "query": "SELECT Id,Name FROM EmailMessage"
        },
        {
            "operation": "Insert",
            "query": "SELECT Body, Id, Name, ParentId$EmailMessage FROM Attachment",
            "master": false
			
        }
      
    ]
    
}

below is the error I'm getting.

[15:05:24.730] [ERROR] Execution of the command has aborted due to unexpected error: Invalid string length.
[15:05:24.779] [ERROR] [STACK TRACE] RangeError: Invalid string length
    at Array.join (<anonymous>)
    at CsvStringifier.joinRecords (C:\Users\PrajwalTajane\AppData\Local\sfdx\node_modules\csv-writer\dist\lib\csv-stringifiers\abstract.js:28:24)
    at CsvStringifier.stringifyRecords (C:\Users\PrajwalTajane\AppData\Local\sfdx\node_modules\csv-writer\dist\lib\csv-stringifiers\abstract.js:19:21)
    at CsvWriter.<anonymous> (C:\Users\PrajwalTajane\AppData\Local\sfdx\node_modules\csv-writer\dist\lib\csv-writer.js:54:61)
    at step (C:\Users\PrajwalTajane\AppData\Local\sfdx\node_modules\csv-writer\dist\lib\csv-writer.js:33:23)
    at Object.next (C:\Users\PrajwalTajane\AppData\Local\sfdx\node_modules\csv-writer\dist\lib\csv-writer.js:14:53)
    at C:\Users\PrajwalTajane\AppData\Local\sfdx\node_modules\csv-writer\dist\lib\csv-writer.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\PrajwalTajane\AppData\Local\sfdx\node_modules\csv-writer\dist\lib\csv-writer.js:4:12)
    at CsvWriter.writeRecords (C:\Users\PrajwalTajane\AppData\Local\sfdx\node_modules\csv-writer\dist\lib\csv-writer.js:49:16)
[15:05:24.785] [ERROR] Execution of the command sfdmu:run has been completed. Exit code 1 (COMMAND_UNEXPECTED_ERROR).

Can you please help me out with this error.

**Comment by hknokh** [comment]
Hello,

Thank you for your message. I will review your issue as soon as possible, but please note that it may take some time to address it thoroughly.
You can learn more about our support policy on our website: [SFDMU support policy](https://help.sfdmu.com/full-documentation/additional-information/support_policy).

Thank you for your understanding and patience.

Best regards.

**Comment by hknokh** [comment]
Hello.

I sincerely apologize for the extended delay in resolving your ticket. I understand that you have been waiting for a resolution, and I regret any inconvenience this has caused.

Due to my current time constraints and commitments, I am unable to provide timely support for this project. However, please be assured that I value your inquiry and will review this ticket again as soon as my schedule permits.

Your patience is greatly appreciated, and I will do my best to address your concerns as soon as possible.

Thank you for your understanding.

Best regards.

**Comment by hknokh** [comment]
I've temporarily closed this case for now and will revisit it in the future. 
Once there's an update or outcome, I will reopen it and notify you.

**Comment by hknokh2** [comment]
Hello,

In reference to the solution mentioned in this issue: https://github.com/forcedotcom/SFDX-Data-Move-Utility/issues/628, you may want to consider reducing the restApiBatchSize for Attachment records to between 5 and 10.

For further details, please consult the updated documentation here: https://help.sfdmu.com/full-documentation/advanced-features/export-attachments-and-files.

Best regards,
