### ISSUE TITLE
[QUESTION]-Unexpected error while trying to export to csv

### ISSUE THREAD

**Issue by mohamedaminem5** [forcedotcom/SFDX-Data-Move-Utility#659]
**Describe the bug**
Hello all, I was installing and learning how to use sfdmu plugin with Salesforce via exporting Account records to csv file. However, I get the following error while running the command in question:

[18:46:36.572] Execution of the command sfdmu:run has been started.
=== Loading and validating the export.json script ...
=== OBJECT SET #1 STARTED
Running Plugin version: 4.30.0
Running Add-On API version: 1.5.0
[18:46:36.657] Loading Core Add-On Module declarations ...
[18:46:36.721] Connecting to the SourceUsername using SFDX force:org:display ...
[18:46:56.526] Successfully connected to the SourceUsername.
[18:46:57.497] Connecting to the Account using SFDX force:org:display ...
[18:47:02.182] [ERROR] [STACK TRACE] Error: Command failed: sfdx force:org:display --json --targetusername Account
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at Common.execSfdx (C:\Users\localusername\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\components\common_components\common.js:196:49)
    at ScriptOrg._setupConnection (C:\Users\localusername\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\script_models\scriptOrg.js:124:53)
    at ScriptOrg.setupAsync (C:\Users\localusername\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\script_models\scriptOrg.js:52:20)
    at Script.setupAsync (C:\Users\localusername\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\models\script_models\script.js:215:30)  
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RunCommand.setupObjectSetAsync (C:\Users\localusername\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\commands_processors\runCommand.js:71:9)
    at async RunCommandExecutor.execute (C:\Users\localusername\AppData\Local\sfdx\node_modules\sfdmu\lib\modules\commands_processors\runCommandExecutor.js:39:17)
[18:47:02.187] [ERROR] Execution of the command sfdmu:run has been completed. Exit code 1 (COMMAND_UNEXPECTED_ERROR).
[18:47:02.190] Total time elapsed: 00h 00m 25s 611ms .

**To Reproduce**
Execution of the following command: sfdx sfdmu:run --sourceusername sourceUserName --targetusername Account --loglevel trace

**Expected behavior**
Account.csv file with account records from SourceUsername

**export.json**
Attach your **export.json** file
[export.json](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/13313876/export.json)

**Log file**
Attach your full **.log** file.

**_target.csv** file.
When you have an issue with failed rows, attach the dump of the **_target.csv** file containing the error messages (at least 1-2 relevant full rows).

**Comment by mohamedaminem5** [comment]
@hknokh I noticed that this issue has been assigned to you, any update on it please? Thanks

**Comment by hknokh2** [comment]
Hello.

Thank you for contacting me, and I apologize for the delayed response. 
Indeed this issue is assigned to me as I'm the sole maintainer of this project :), but unfortunately, I currently have limited time to dedicate to consistent maintenance.

Regarding your issue, it seems you might not have an SFDX org named "Account" set up on your local system. The command you're using:
```sfdx sfdmu:run --sourceusername sourceUserName --targetusername Account --loglevel trace```
implies that 'Account' is being used as a target username. 
However, the target username should be a Salesforce username or an organization alias, not an object name. 
Please verify this detail.

Best regards.

**Comment by mohamedaminem5** [comment]
Hi @hknokh2 , thank you for your reply. What I am trying to do is to export Account records to a CSV file and not directly to another Salesforce org. What is the syntax I should be using? sfdx sfdmu:run --sourceusername sourceUserName --targetusername Account.csv --loglevel trace?

**Comment by hknokh** [comment]
Use 'csvfile' as the target username in the command:
```sfdx sfdmu:run --sourceusername sourceUserName --targetusername csvfile --loglevel trace```
This configuration will enable the tool to automatically find and use the relevant CSV files.
