### ISSUE TITLE
[QUESTION]- Migrate Attachments or Files failed

### ISSUE THREAD

**Issue by unizhu** [forcedotcom/SFDX-Data-Move-Utility#682]
Looks like this issue:

[https://github.com/forcedotcom/SFDX-Data-Move-Utility/issues/628](url)

Migrate Accounts' attachments:

`
{
            "operation": "Insert",
            "query": "SELECT Body, Id, Name, OwnerId, ParentId$Account FROM Attachment",
            "master": false
 }
`

`
=== Data retrieval summary.
[13:54:28.893] {User} The total amount of the retrieved records: 15109/351.
[13:54:28.894] {Account} The total amount of the retrieved records: 2281/6693.
[13:54:28.894] {Calendar} The total amount of the retrieved records: 0/0.
[13:54:28.894] {Attachment} The total amount of the retrieved records: **329**/0.
[13:54:28.894] {Note} The total amount of the retrieved records: 0/0.
=== Updating the Target (STAGE 1) ...
WARNING: [13:54:28.901] [WARN] {Attachment} **344**  _(Greater than total amount)❓_  missing parent lookup records were found. See MissingParentRecordsReport.csv file for the details.
[13:54:28.904] [13:54:28.904] Continue the job (y/n) ? y

[13:54:28.907] {Attachment} The Insert API operation has been started using REST API.
Command in progress... done

[13:54:31.224] [ERROR] Execution of the command has aborted due to unexpected error: Invalid string length.
[13:54:31.225] [ERROR] [STACK TRACE] RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at Connection._createMany (/Users/uni/.local/share/sf/node_modules/sfdmu/node_modules/jsforce/lib/connection.js:834:17)
    at Connection._createMany (/Users/uni/.local/share/sf/node_modules/sfdmu/node_modules/jsforce/lib/connection.js:813:17)
    at Connection.insert.Connection.create (/Users/uni/.local/share/sf/node_modules/sfdmu/node_modules/jsforce/lib/connection.js:759:14)
    at SObject.insert.SObject.create (/Users/uni/.local/share/sf/node_modules/sfdmu/node_modules/jsforce/lib/sobject.js:62:21)
    at /Users/uni/.local/share/sf/node_modules/sfdmu/lib/modules/components/api_engines/restApiEngine.js:81:66
    at new Promise (<anonymous>)
    at RestApiEngine.processCRUDApiBatchAsync (/Users/uni/.local/share/sf/node_modules/sfdmu/lib/modules/components/api_engines/restApiEngine.js:44:16)
    at RestApiEngine.processCRUDApiJobAsync (/Users/uni/.local/share/sf/node_modules/sfdmu/lib/modules/models/api_models/ApiEngineBase.js:143:44)
    at RestApiEngine.executeCRUD (/Users/uni/.local/share/sf/node_modules/sfdmu/lib/modules/models/api_models/ApiEngineBase.js:95:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RestApiEngine.executeCRUDMultithreaded (/Users/uni/.local/share/sf/node_modules/sfdmu/lib/modules/models/api_models/ApiEngineBase.js:102:20)
    at async ___updateData (/Users/uni/.local/share/sf/node_modules/sfdmu/lib/modules/models/job_models/migrationJobTask.js:842:37)
    at async MigrationJobTask.updateRecords (/Users/uni/.local/share/sf/node_modules/sfdmu/lib/modules/models/job_models/migrationJobTask.js:670:45)
    at async MigrationJob.updateRecordsAsync (/Users/uni/.local/share/sf/node_modules/sfdmu/lib/modules/models/job_models/migrationJob.js:321:43)
    at async RunCommand.executeJobAsync (/Users/uni/.local/share/sf/node_modules/sfdmu/lib/modules/commands_processors/runCommand.js:105:9)
[13:54:31.226] [ERROR] Execution of the command sfdmu:run has been completed. Exit code 1 (COMMAND_UNEXPECTED_ERROR).
[13:54:31.226] Total time elapsed: 00h 46m 43s 973ms .
`

**Comment by hknokh** [comment]
Hello,

Thank you for your message. I appreciate your patience. Currently, I have limited availability for project support, which means that resolving your issue may take an extended period of time.

You can find more details about our support policy on our website: [SFDMU support policy](https://help.sfdmu.com/full-documentation/additional-information/support_policy).

Thank you for your understanding and for bearing with any potential delays.

Best regards.

**Comment by hknokh2** [comment]
Hello,

I've successfully tested the export of 9,000 attachments related to Accounts. I noticed that when parent IDs are missing, the process doesn't fail; it merely indicates that parent records are missing. Could you please confirm which version of SFDMU you are currently using? I recommend verifying this with the latest version of SFDMU. Additionally, could you provide the complete export.json file and the full log file for further analysis?

Thank you.

**Comment by unizhu** [comment]
Hello,

After the exception occurred , I tried with restApiBatchSize set to 5 - 10, it works. Migrated around 1000+ attachments. Thanks.

**Comment by hknokh2** [comment]
Thank you for the update, I will add this solution to the official documentation.

**Comment by hknokh** [comment]
Hello.
 
This case is now considered resolved, and I am closing it for now. If you have any additional questions or concerns, please don't hesitate to reach out.

Regards.
