### ISSUE TITLE
[ERROR] Execution of the command was ABORTED due to unexpected error: line 1:0 mismatched input '<EOF>' expecting SELECT.

### ISSUE THREAD

**Issue by jrattanpal** [forcedotcom/SFDX-Data-Move-Utility#98]
I am trying to export and Import Person Accounts. Export to CSV is working fine but import from CSV is failing with following error.

Description says "full support" for person account so how do I achieve this?
And how will it work to map following objects (say Lead) with those contacts which are created as part of PersonAccount?

[export.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/4806360/export.txt)

=== PREPARING DATA MIGRATION JOB...
Order of objects to retrieve data: OperatingHours; Account; Contact
Order of objects to update data: OperatingHours; Account; Contact
Validating and repairing of the source CSV files...
Command in progress...... done
[ERROR] Execution of the command was ABORTED due to unexpected error: line 1:0 mismatched input '<EOF>' expecting SELECT.
[STACK TRACE] Error: line 1:0 mismatched input '<EOF>' expecting SELECT
    at SyntaxErrorListener.syntaxError (/Users/XXX/.local/share/sfdx/node_modules/soql-parser-js/dist/index.js:382:15)
    at delegates.forEach.listener (/Users/XXX/.local/share/sfdx/node_modules/antlr4ts/ProxyErrorListener.js:37:26)
    at Array.forEach (<anonymous>)
    at ProxyParserErrorListener.syntaxError (/Users/XXX/.local/share/sfdx/node_modules/antlr4ts/ProxyErrorListener.js:35:24)
    at SOQLParser.notifyErrorListeners (/Users/XXX/.local/share/sfdx/node_modules/antlr4ts/Parser.js:388:22)
    at DefaultErrorStrategy.notifyErrorListeners (/Users/XXX/.local/share/sfdx/node_modules/antlr4ts/DefaultErrorStrategy.js:132:20)
    at DefaultErrorStrategy.reportInputMismatch (/Users/XXX/.local/share/sfdx/node_modules/antlr4ts/DefaultErrorStrategy.js:287:14)
    at DefaultErrorStrategy.reportError (/Users/XXX/.local/share/sfdx/node_modules/antlr4ts/DefaultErrorStrategy.js:115:18)
    at SOQLParser.select_clause (/Users/XXX/.local/share/sfdx/node_modules/soql-parser-js/dist/index.js:7439:34)
    at SOQLParser.soql_query (/Users/XXX/.local/share/sfdx/node_modules/soql-parser-js/dist/index.js:7285:22)
Execution of the command sfdmu:run has been finished. Exit code 1 (COMMAND_UNEXPECTED_ERROR).
Total time elapsed: 00h 00m 06s 865ms .

**Comment by hknokh** [comment]
Hello @jrattanpal 
Can you please provide me your export.json file and the full last .log file.
Thank you!

**Comment by hknokh** [comment]
Hello @jrattanpal 
I think I've found and solved the issue.
Please retest and let me know if it is working.
If still no, please send me the export.json and .log file.
Thanks!

**Comment by jrattanpal** [comment]
Thank you! That worked
